// 블로그 콘텐츠 — blog.html(목록) / blog-*.html(포스트)에서 사용. region-content.js와 동일하게
// 언어별(ko/en) 콘텐츠를 데이터로 분리해두고, js/blog.js가 getLang()에 맞춰 렌더링한다.

const BLOG_LIST = [
  {
    slug: "taipei-beef-noodle",
    image: "assets/images/blog/taipei-beef-noodle-bowl-1.webp",
    ko: {
      eyebrow: "타이베이 미식 가이드 · 우육면",
      title: "대만 사람도 결국 한 그릇으로 돌아오는, 타이베이 우육면 순례",
      desc: "홍샤오 우육면은 어디서 왔고, 왜 대만인의 소울푸드가 됐을까요. 여행자들이 실제로 다녀와 남긴 타이베이 우육면집까지 한 번에 정리했어요.",
      meta: "타이베이 · 우육면(牛肉麵)",
    },
    en: {
      eyebrow: "Taipei Food Guide · Beef Noodle Soup",
      title: "Why Beef Noodle Soup Is the Dish Every Taiwanese Comes Back To",
      desc: "Where Hong Shao beef noodle soup came from, and why it became Taiwan's soul food — plus real traveler reviews of beef noodle shops in Taipei.",
      meta: "Taipei · Beef Noodle Soup (牛肉麵)",
    },
  },
];

const BLOG_POSTS = {
  "taipei-beef-noodle": {
    heroImage: "assets/images/blog/taipei-beef-noodle-bowl-1.webp",
    ko: {
      pageTitle: "타이베이 우육면 순례 · 나만 알고 싶은 대만 맛집",
      metaDescription: "우육면의 역사와 대만인이 사랑하는 이유부터, 타이베이 우육면집 6곳 여행자 후기까지. 타이베이 우육면 맛집 가이드.",
      ogTitle: "타이베이 우육면 순례",
      eyebrow: "타이베이 미식 가이드 · 우육면",
      title: "대만 사람도 결국 한 그릇으로 돌아오는,<br>타이베이 우육면 순례",
      dek: "국물 한 숟갈에 팔각과 두반장 향이 확 올라오는 홍샤오 우육면. 어디서 왔고, 왜 대만인의 소울푸드가 됐는지부터 — 여행자들이 실제로 다녀와 남긴 타이베이 우육면집 6곳까지 한 번에 정리했어요.",
      metaAuthor: "나만 알고 싶은 대만 맛집 편집팀",
      metaTopic: "타이베이 · 우육면(牛肉麵)",
      metaReadTime: "약 6분 소요",
      intro: "우육면(牛肉麵)은 이름만 보면 대륙 어딘가에서 건너온 음식 같지만, 지금 대만 어디서나 만나는 진한 <strong>홍샤오(紅燒) 우육면</strong>은 대만 땅에서 완성된 요리예요. 대만 사람들 스스로도 \"가장 대만다운 대륙 음식\"이라고 부르는 이유가 여기 있어요.",
      h2_1: "01 · 우육면, 사실은 대만에서 태어난 맛",
      timeline: [
        { year: "1949년", desc: "국공내전에서 물러난 국민당과 함께 수십만 명이 대만으로 이주해요. 그중에는 쓰촨·구이저우 출신 군인과 그 가족들이 모여 산 '쥐안춘(眷村)' 마을이 여럿 생겼어요." },
        { year: "1960년대, 가오슝 강산(岡山)", desc: "공군 기지 근처 쥐안춘에서 고향의 두반장(豆瓣醬) 레시피에 소·미국 원조 밀가루로 뽑은 면을 더한 것이 지금 홍샤오 우육면의 원형으로 꼽혀요. 사실 쓰촨 본토에는 이런 형태의 우육면이 따로 없었다는 게 재미있는 지점이에요." },
        { year: "1970~80년대", desc: "강산의 두반장 산업과 함께 이 레시피가 북쪽으로 퍼지면서, 타이베이 타오위안제(桃源街) 일대에 우육면 노포가 줄줄이 들어서 '우육면 거리'로 불리게 돼요." },
        { year: "2005년~", desc: "타이베이시가 '타이베이 국제우육면절(台北牛肉麵節)'을 시작하면서, 골목 노포 음식이던 우육면이 대만을 대표하는 미식 콘텐츠로 완전히 자리 잡아요." },
      ],
      figure1Caption: "대만에서 만난 홍샤오 우육면 — 진한 간장 육수에 큼직한 소고기가 듬뿍 올라간다.",
      afterTimeline: "참고로 국물은 크게 두 갈래예요. 간장·두반장·팔각·계피로 진하게 끓여 색이 붉고 살짝 매콤한 <strong>홍샤오(紅燒)</strong>, 그리고 향신료 없이 맑게 고아낸 <strong>칭둔(清燉)</strong>. 대만에서 그냥 \"우육면 먹으러 가자\"고 하면 열에 아홉은 홍샤오를 뜻해요.",
      h2_2: "02 · 대만 사람들은 왜 우육면에 진심일까",
      reasonsIntro: "대만 어디를 가나 우육면집이 있고, 다들 \"우리 동네 우육면이 제일\"이라는 나름의 기준이 있어요. 그 이유를 뜯어보면 크게 두 가지로 정리돼요.",
      reasons: [
        { ico: "🍜", title: "이민자들이 만든 '진짜' 국민음식", desc: "특정 지역 고유의 향토음식이 아니라 여러 성(省) 출신이 뒤섞이며 대만 땅에서 새로 태어난 요리라, 특정 지역을 대표하기보다 대만 전체를 대표하는 음식으로 여겨져요." },
        { ico: "🏆", title: "한 그릇에 걸린 자존심", desc: "육수를 몇 시간 우렸는지, 두반장 배합이 어떤지로 가게마다 승부를 봐요. 국제우육면절에서 매년 순위를 가릴 만큼, 대만인에게 우육면은 여전히 경쟁하고 발전시킬 가치가 있는 요리예요." },
      ],
      quote: "\"우육면 한 그릇이면 아침이든 밤 11시든 다 통한다.\" — 대만에서는 시간을 가리지 않고 먹는 몇 안 되는 메인 요리예요.",
      h2_3: "03 · 타이베이에서 다녀온 사람들이 남긴 우육면 6곳",
      spotsIntro: "아래는 '나만 알고 싶은 대만 맛집' 지도에 여행자들이 직접 등록한 타이베이 우육면집이에요. 화려한 순위표가 아니라, 실제로 먹어본 사람들의 한 줄 후기를 그대로 모았어요.",
      spots: [
        { name: "라오장 우육면", tag: "다안구 · Da'an", html: "다녀온 여행자들이 입을 모아 <em>\"여기도 맛 괜찮습니다\"</em>, <em>\"우육면과 같이 먹으니 좋았어요\"</em>라고 남겼어요. 근처 다른 맛집과 묶어 코스로 들르기 좋은 곳으로 언급돼요.", link: "https://maps.app.goo.gl/53ZxCfM2QdWrrZdCA", linkLabel: "구글맵에서 위치 보기 →" },
        { name: "Halal Chinese Beef Noodles", tag: "다안구 · Da'an", html: "여행자 후기는 짧고 굵게 <em>\"맛있다고 강력 추천\"</em>. 무슬림 여행자를 위한 할랄 인증 우육면집이 흔치 않은 만큼, 일행 중 할랄 식단이 필요한 분이 있다면 특히 기억해둘 만해요.", link: "https://www.google.com/maps/place/Halal+Chinese+Beef+Noodles+(Da'an)/@25.0420706,121.5549566,17z", linkLabel: "구글맵에서 위치 보기 →" },
        { name: "푸홍 우육면", tag: "시먼 인근 · Ximen area", html: "현지 매운맛을 즐긴다면 참고할 팁 하나 — <em>\"빨간 소스 넣으면 얼큰해서 더 맛있음\"</em>. 테이블에 놓인 라유·고추기름을 취향껏 더해 국물 맛을 직접 조절해볼 수 있어요.", link: "https://www.google.com/maps/search/?api=1&query=25.0476197,121.5077358", linkLabel: "구글맵에서 위치 보기 →" },
        { name: "味妙牛肉麵 (웨이먀오 우육면)", tag: null, html: "등록된 후기는 짧지만 명확해요 — <em>\"우육면으로 추천\"</em>.", link: "https://maps.app.goo.gl/S5nynqNKNKDr3QqQ7", linkLabel: "구글맵에서 위치 보기 →" },
        { name: "A E Beef Noodle Restaurant (아어 우육면)", tag: "완화구 · Wanhua", html: "완화(용산사) 쪽에서 우육면이 당길 때 들를 만한 곳으로 지도에 새로 등록됐어요. 아직 한 줄 후기가 쌓이지 않았으니, 다녀오셨다면 지도에 첫 리뷰를 남겨주세요.", link: "https://maps.app.goo.gl/US3Pin2JBNckERee9", linkLabel: "구글맵에서 위치 보기 →" },
        { name: "삼가 우육면", tag: "완화구 인근 · Wanhua area", html: "역시 최근에 새로 등록된 곳이라 아직 후기는 없어요. 완화 지역 우육면 옵션을 늘려두고 싶다면 체크해두기 좋아요.", link: "https://maps.app.goo.gl/VU2WjkC9Z1ok4x7YA", linkLabel: "구글맵에서 위치 보기 →" },
      ],
      figure2Caption: "가게마다 면발과 고명 구성이 조금씩 다른 것도 우육면을 순례하는 재미 중 하나.",
      h2_4: "04 · 주문 전에 알아두면 좋은 것들",
      tips: [
        { mark: "紅", b: "홍샤오 vs 칭둔", desc: "처음이라면 무조건 홍샤오(紅燒)로 시작하세요. 진하고 살짝 매콤한 국물이 대만 우육면의 기본값이에요." },
        { mark: "麵", b: "牛肉麵 vs 牛肉湯麵, 헷갈리면 안 돼요", desc: "牛肉麵(뉴러우몐)은 고기가 들어간 우육면이고, 牛肉湯麵(뉴러우탕몐)은 고기 없이 국물과 면만 나오는 메뉴예요. 소고기를 기대하고 시켰다가 국물만 받는 일이 없도록 메뉴판의 한자를 꼭 확인하세요." },
        { mark: "辣", b: "매운맛은 셀프", desc: "국물 자체는 맵기보다 향신료 향이 강한 편이라, 테이블에 있는 고추기름을 조금씩 더해가며 내 입맛대로 맞추는 게 정석이에요." },
      ],
      ctaTitle: "지도에서 우육면 맛집 더 보기",
      ctaDesc: "타이베이 전체 우육면 스팟과 실시간 후기를 지도에서 바로 확인해보세요.",
      ctaBtn: "지도 열기 →",
      sourcesPrefix: "참고자료 — 우육면의 역사와 가오슝 강산 기원설:",
      sourcesSuffix: "맛집 후기는 '나만 알고 싶은 대만 맛집' 지도에 여행자들이 직접 등록한 내용을 바탕으로 요약했습니다.",
    },
    en: {
      pageTitle: "A Taipei Beef Noodle Soup Pilgrimage · My Secret Taiwan Eats",
      metaDescription: "The history of beef noodle soup, why Taiwanese people love it, and real traveler reviews of six beef noodle shops in Taipei.",
      ogTitle: "A Taipei Beef Noodle Soup Pilgrimage",
      eyebrow: "Taipei Food Guide · Beef Noodle Soup",
      title: "Why Beef Noodle Soup Is the Dish Every<br>Taiwanese Comes Back To",
      dek: "One spoonful of the broth and you get a hit of star anise and doubanjiang. Where Hong Shao beef noodle soup came from, why it became Taiwan's soul food, and six Taipei shops real travelers have actually visited.",
      metaAuthor: "My Secret Taiwan Eats Editorial",
      metaTopic: "Taipei · Beef Noodle Soup (牛肉麵)",
      metaReadTime: "About 6 min read",
      intro: "Beef noodle soup (牛肉麵) sounds like something that crossed over from mainland China, but the rich <strong>Hong Shao (紅燒, braised)</strong> version found everywhere in Taiwan today was actually perfected on Taiwanese soil. Taiwanese people themselves call it \"the most Taiwanese mainland dish\" — here's why.",
      h2_1: "01 · Beef Noodle Soup Was Actually Born in Taiwan",
      timeline: [
        { year: "1949", desc: "Hundreds of thousands of people relocated to Taiwan alongside the Nationalist government after its defeat in the Chinese Civil War. Among them were soldiers from Sichuan and Guizhou and their families, who formed several \"military dependents' villages\" (眷村)." },
        { year: "1960s, Gangshan, Kaohsiung", desc: "In a dependents' village near an air force base, soldiers combined their hometown doubanjiang (豆瓣醬, spicy bean paste) recipe with noodles made from U.S. food-aid flour and beef — the prototype of today's Hong Shao beef noodle soup. Interestingly, this exact style never actually existed in mainland Sichuan." },
        { year: "1970s–80s", desc: "As Gangshan's doubanjiang industry grew, the recipe spread north, and a strip of beef noodle shops sprang up along Taoyuan Street (桃源街) in Taipei, earning it the nickname \"Beef Noodle Street.\"" },
        { year: "2005–present", desc: "The City of Taipei launched the Taipei International Beef Noodle Festival (台北牛肉麵節), turning what had been humble neighborhood fare into one of Taiwan's signature food events." },
      ],
      figure1Caption: "Hong Shao beef noodle soup found in Taiwan — a rich soy-based broth piled with generous chunks of beef.",
      afterTimeline: "The broth generally comes in two styles: <strong>Hong Shao (紅燒)</strong>, simmered dark and slightly spicy with soy sauce, doubanjiang, star anise and cinnamon; and <strong>Qing Dun (清燉)</strong>, a clear broth with no spices. In Taiwan, if someone just says \"let's get beef noodle soup,\" nine times out of ten they mean Hong Shao.",
      h2_2: "02 · Why Taiwanese People Are So Passionate About Beef Noodle Soup",
      reasonsIntro: "There's a beef noodle shop on nearly every block in Taiwan, and everyone has their own opinion about which neighborhood spot is the best. It comes down to two big reasons.",
      reasons: [
        { ico: "🍜", title: "A \"real\" national dish, made by immigrants", desc: "Rather than being a local specialty tied to one region, it was born in Taiwan out of a mix of provinces from mainland China — so it's seen as representing all of Taiwan rather than just one area." },
        { ico: "🏆", title: "Pride staked on a single bowl", desc: "Shops compete on how many hours they simmer the broth and their own doubanjiang blend. The beef noodle festival crowns winners every year — proof that, for Taiwanese people, this dish is still worth competing over and perfecting." },
      ],
      quote: "\"A bowl of beef noodle soup works whether it's morning or 11pm.\" — It's one of the few main dishes Taiwanese people eat any time of day.",
      h2_3: "03 · Six Beef Noodle Shops in Taipei, Reviewed by Travelers Who've Actually Been",
      spotsIntro: "Below are Taipei beef noodle shops that travelers have registered themselves on the My Secret Taiwan Eats map. Instead of a flashy ranking, these are real one-line reviews from people who actually ate there.",
      spots: [
        { name: "Lao Zhang Beef Noodles", tag: "Da'an District", html: "Travelers who've visited agree — <em>\"pretty good here too\"</em>, <em>\"was nice to eat alongside the beef noodle soup.\"</em> Mentioned as a good stop to pair with other nearby restaurants on a food-hopping route.", link: "https://maps.app.goo.gl/53ZxCfM2QdWrrZdCA", linkLabel: "View on Google Maps →" },
        { name: "Halal Chinese Beef Noodles", tag: "Da'an District", html: "Short and to the point — <em>\"delicious, highly recommend.\"</em> Halal-certified beef noodle shops are rare in Taipei, so this one is worth remembering if anyone in your group needs halal food.", link: "https://www.google.com/maps/place/Halal+Chinese+Beef+Noodles+(Da'an)/@25.0420706,121.5549566,17z", linkLabel: "View on Google Maps →" },
        { name: "Fuhong Beef Noodles", tag: "Near Ximen", html: "A tip for spice lovers — <em>\"adding the red sauce makes it spicier and even better.\"</em> You can adjust the broth yourself with the chili oil left on the table.", link: "https://www.google.com/maps/search/?api=1&query=25.0476197,121.5077358", linkLabel: "View on Google Maps →" },
        { name: "Weimiao Beef Noodles (味妙牛肉麵)", tag: null, html: "The review on file is short but clear — <em>\"recommended for beef noodle soup.\"</em>", link: "https://maps.app.goo.gl/S5nynqNKNKDr3QqQ7", linkLabel: "View on Google Maps →" },
        { name: "A E Beef Noodle Restaurant", tag: "Wanhua District", html: "Newly added to the map — a solid option near Wanhua (Longshan Temple) when you're craving beef noodle soup. No reviews yet, so if you've been, please leave the first one on the map.", link: "https://maps.app.goo.gl/US3Pin2JBNckERee9", linkLabel: "View on Google Maps →" },
        { name: "Sanjia Beef Noodles", tag: "Near Wanhua", html: "Also newly added, with no reviews yet. Worth bookmarking if you want more beef noodle options around Wanhua.", link: "https://maps.app.goo.gl/VU2WjkC9Z1ok4x7YA", linkLabel: "View on Google Maps →" },
      ],
      figure2Caption: "Every shop's noodles and toppings are a little different — part of the fun of a beef noodle pilgrimage.",
      h2_4: "04 · Good to Know Before You Order",
      tips: [
        { mark: "紅", b: "Hong Shao vs. Qing Dun", desc: "If it's your first time, start with Hong Shao (紅燒). A rich, slightly spicy broth is the default for Taiwanese beef noodle soup." },
        { mark: "麵", b: "Don't mix up 牛肉麵 and 牛肉湯麵", desc: "牛肉麵 (niu rou mian) comes with beef in it, while 牛肉湯麵 (niu rou tang mian) is just broth and noodles with no meat. Double-check the characters on the menu so you don't order expecting beef and get only broth." },
        { mark: "辣", b: "Spice level is up to you", desc: "The broth itself leans more fragrant-with-spices than outright spicy, so adding chili oil from the table little by little to match your taste is the standard move." },
      ],
      ctaTitle: "See More Beef Noodle Spots on the Map",
      ctaDesc: "Check every beef noodle soup spot in Taipei, plus live traveler reviews, right on the map.",
      ctaBtn: "Open Map →",
      sourcesPrefix: "Sources — on the history of beef noodle soup and its origin story in Gangshan, Kaohsiung:",
      sourcesSuffix: "Restaurant reviews were summarized from entries travelers registered themselves on the My Secret Taiwan Eats map.",
    },
  },
};
