// 블로그 콘텐츠 — blog.html(목록) / blog-*.html(포스트)에서 사용. region-content.js와 동일하게
// 언어별(ko/en) 콘텐츠를 데이터로 분리해두고, js/blog.js가 getLang()에 맞춰 렌더링한다.
//
// 포스트 본문은 post[lang].blocks 배열(정보형 가이드용 범용 스키마)로 구성한다. 지원하는 block.type:
//   "p"            { html }                                              — 문단
//   "h2"           { text }                                              — 소제목
//   "compareTable" { cities: [string,...], rows: [{ label, values: [...] }] } — 비교 표
//   "cityGrid"     { items: [{ img, name, tag, desc }] }                 — 도시별 이미지 카드
//   "figure"       { img, caption }                                     — 본문 중간에 넣는 이미지 한 장(예전 히어로 사진 등)
//   "figureGrid"   { items: [{ img, caption }] }                         — 이미지 여러 장
//   "quote"        { text }                                              — 인용구
//   "tipList"      { items: [{ mark, b, desc }] }                        — 마크+제목+설명 리스트
//   "cta"          { title, desc, btn, href }                            — 지도 유도 CTA
//   "note"         { text }                                              — 하단 안내 문구(출처 등)
//
// BLOG_LIST 항목의 regions: [...]는 js/data.js의 REGIONS id(taipei, taichung, kaohsiung, tainan, ...)를 그대로 쓴다.
// blog.js가 이 값으로 목록 페이지의 지역 필터 탭을 만든다. 여러 지역을 다루는 글이면 배열에 모두 적는다.

const BLOG_LIST = [
  {
    slug: "taipei-taichung-kaohsiung-with-mom",
    image: "assets/images/regions/taipei.webp",
    regions: ["taipei", "taichung", "kaohsiung"],
    ko: {
      eyebrow: "대만 여행 가이드 · 도시 선택",
      title: "타이베이·타이중·가오슝, 엄마와 가는 첫 대만 여행 어디가 편할까",
      desc: "이동 난이도, 관광 밀도, 부모님 동선까지 — 세 도시를 비교해서 첫 대만 여행지를 골라봤습니다.",
      meta: "대만 여행 · 도시 비교",
    },
    en: {
      eyebrow: "Taiwan Travel Guide · Choosing a City",
      title: "Taipei vs. Taichung vs. Kaohsiung: Best First City for a Trip with Mom",
      desc: "Comparing transit difficulty, sightseeing density, and how easy the walking is — to help pick a first Taiwan destination with a parent.",
      meta: "Taiwan Travel · City Comparison",
    },
  },
  {
    slug: "taipei-easycard-transport-guide",
    image: "assets/images/blog/taipei-taxi-night-market.jpg",
    regions: ["taipei"],
    ko: {
      eyebrow: "타이베이 여행 가이드 · 교통",
      title: "타이베이 첫 여행 3박4일, 이지카드만으로 충분할까?",
      desc: "이지카드, 신용카드 컨택리스 결제, 버스, 택시(우버)까지 — 첫 타이베이 여행자를 위한 교통수단 총정리.",
      meta: "타이베이 · 교통 가이드",
    },
    en: {
      eyebrow: "Taipei Travel Guide · Transportation",
      title: "Taipei First Trip, 4 Days 3 Nights: Is an EasyCard Enough?",
      desc: "EasyCard, contactless credit cards, buses, and taxis (Uber) — a complete transportation rundown for first-time Taipei visitors.",
      meta: "Taipei · Transportation Guide",
    },
  },
  {
    slug: "taipei-souvenir-gift-guide",
    image: "assets/images/blog/taiwan-pineapple-tart.jpg",
    regions: ["taipei"],
    ko: {
      eyebrow: "타이베이 여행 가이드 · 선물",
      title: "대만 여행 선물 추천 — 뻔한 간식 말고 뭘 사올까?",
      desc: "펑리수·누가크래커는 다들 사 오는 국룰이죠. 그래도 새로운 선물을 찾는다면, 브랜드별 비교와 가성비 팁까지 정리했어요.",
      meta: "타이베이 · 선물 가이드",
    },
    en: {
      eyebrow: "Taipei Travel Guide · Souvenirs",
      title: "Taiwan Souvenir Guide: What to Bring Home Besides the Usual Snacks",
      desc: "Pineapple cake and nougat crackers are the classic picks. Here's a brand comparison and budget tips for when you want something different.",
      meta: "Taipei · Souvenir Guide",
    },
  },
  {
    slug: "taipei-overnight-red-eye-flight-last-day",
    image: "assets/images/blog/taipei-chiang-kai-shek-hall-night.jpg",
    regions: ["taipei"],
    ko: {
      eyebrow: "타이베이 여행 가이드 · 일정 팁",
      title: "타이베이 마지막 날, 숙박 없이 새벽 비행기 타도 될까?",
      desc: "마지막 날 밤 숙소를 잡지 않고 새벽 비행기를 타는 '무박' 일정. 실제 여행자들의 경험을 바탕으로 장단점과 시간 활용법을 정리했어요.",
      meta: "타이베이 · 일정 가이드",
    },
    en: {
      eyebrow: "Taipei Travel Guide · Itinerary Tips",
      title: "Taipei Last Day: Can You Skip the Hotel and Catch a Red-Eye Flight?",
      desc: "Checking out and spending the whole last day out before a 2-3am flight, no extra hotel night. Real traveler experiences on the pros, cons, and how to spend the time.",
      meta: "Taipei · Itinerary Guide",
    },
  },
  {
    slug: "taipei-liquid-checked-baggage-guide",
    image: "assets/images/blog/taiwan-pineapple-tart.jpg",
    regions: ["taipei"],
    ko: {
      eyebrow: "타이베이 여행 가이드 · 쇼핑·수하물",
      title: "대만 간식·술, 기내 반입 될까 위탁수하물로 부쳐야 할까",
      desc: "젤리·푸딩 같은 말랑한 간식부터 고량주까지 — 액체·젤류 반입 기준과 주류 면세 한도를 한 번에 정리했어요.",
      meta: "타이베이 · 쇼핑 가이드",
    },
    en: {
      eyebrow: "Taipei Travel Guide · Shopping & Baggage",
      title: "Taiwan Snacks and Liquor: Carry-On or Checked Baggage?",
      desc: "From jelly cups and pudding snacks to Kaoliang liquor — what counts as a liquid at security, and Korea's duty-free alcohol allowance.",
      meta: "Taipei · Shopping Guide",
    },
  },
  {
    slug: "taipei-xiangde-peking-duck-half-day-course",
    image: "assets/images/regions/taipei.webp",
    regions: ["taipei"],
    ko: {
      eyebrow: "타이베이 여행 가이드 · 맛집 코스",
      title: "베이징덕 맛집 샹덕(享鴨) 먹고 어디 갈까 — 중샤오둔화 반나절 코스",
      desc: "예약 필수인 베이징덕 맛집 샹덕에서 식사하고, 도보·MRT로 가볍게 돌아볼 수 있는 주변 반나절 코스를 짜봤어요.",
      meta: "타이베이 · 맛집 코스",
    },
    en: {
      eyebrow: "Taipei Travel Guide · Food Course",
      title: "What's Near Xiang Duck (享鴨)? A Half-Day Course Around Zhongxiao Dunhua",
      desc: "A half-day route built around Xiang Duck, the reservation-only Peking duck specialist — shopping, a park, and a culture park all within a station or two.",
      meta: "Taipei · Food Course",
    },
  },
  {
    slug: "jiufen-friday-vs-sunday-crowds",
    image: "assets/images/regions/jiufen.webp",
    regions: ["jiufen"],
    ko: {
      eyebrow: "지우펀 여행 가이드 · 방문 타이밍",
      title: "지우펀, 금요일 vs 일요일 언제 덜 붐빌까",
      desc: "초등학생 자녀와 함께라면 특히 중요한 혼잡도 문제. 요일별·시간대별 체감 혼잡도와 방문 타이밍 팁을 정리했어요.",
      meta: "지우펀 · 방문 타이밍",
    },
    en: {
      eyebrow: "Jiufen Travel Guide · Timing Your Visit",
      title: "Jiufen: Friday vs. Sunday, Which Day Is Less Crowded?",
      desc: "Especially important when traveling with young kids — a breakdown of how crowded Jiufen gets by day and time, and how to time your visit.",
      meta: "Jiufen · Timing Your Visit",
    },
  },
  {
    slug: "taipei-longshan-temple-night-guide",
    image: "assets/images/regions/taipei.webp",
    regions: ["taipei"],
    ko: {
      eyebrow: "타이베이 여행 가이드 · 야경 코스",
      title: "용산사는 낮보다 밤? 야경 시간대와 주변 코스 짜는 법",
      desc: "붐비는 낮 시간을 피해 야경으로 즐기는 용산사. 방문 시간대별 분위기 차이와 완화 야시장 연계 코스를 정리했어요.",
      meta: "타이베이 · 야경 코스",
    },
    en: {
      eyebrow: "Taipei Travel Guide · Night View Course",
      title: "Longshan Temple: Better at Night Than by Day?",
      desc: "How the atmosphere changes after dark, and a route linking the temple with Wanhua's night markets.",
      meta: "Taipei · Night View Course",
    },
  },
];

const BLOG_POSTS = {
  "taipei-taichung-kaohsiung-with-mom": {
    heroImage: "assets/images/regions/taipei.webp",
    ko: {
      pageTitle: "타이베이·타이중·가오슝 비교 — 엄마와 가는 첫 대만 여행지 고르기 · 나만 알고 싶은 대만 맛집",
      metaDescription: "부모님과 함께하는 첫 대만 여행, 어느 도시가 좋을까요? 이동 난이도·관광 밀도·부모님 동선 관점에서 타이베이·타이중·가오슝을 비교했습니다.",
      ogTitle: "타이베이·타이중·가오슝, 엄마와 가는 첫 대만 여행 어디가 편할까",
      eyebrow: "대만 여행 가이드 · 도시 선택",
      title: "타이베이·타이중·가오슝, 엄마와 가는 첫 대만 여행 어디가 편할까",
      dek: "이동 수단, 볼거리 밀도, 그리고 무엇보다 부모님이 걷기 편한 동선까지 — 세 도시를 나란히 비교해서 첫 대만 여행지를 골라봤습니다.",
      metaAuthor: "나만 알고 싶은 대만 맛집 편집팀",
      metaTopic: "대만 여행 · 도시 비교",
      intro: "부모님을 모시고 떠나는 첫 대만 여행이라면 도시 선택부터 고민이 깊어집니다. <strong>타이베이</strong>는 두말할 것 없이 기본값이지만, 일정이 며칠 더 남는다면 <strong>타이중</strong>과 <strong>가오슝</strong> 중 어디를 더할지가 관건이에요. 이동 난이도, 관광 밀도, 그리고 무엇보다 부모님이 걷고 이동하기에 편한 동선까지 — 세 가지 기준으로 비교해봤습니다.",
      blocks: [
        { type: "h2", text: "01 · 세 도시, 한눈에 비교하기" },
        {
          type: "compareTable",
          cities: ["타이베이", "타이중", "가오슝"],
          rows: [
            { label: "이동 난이도", values: ["MRT 노선이 촘촘해서 도보 이동이 거의 없습니다", "버스 의존도가 높고 MRT가 주요 관광지를 비껴가는 구간이 많아요", "MRT와 경전철(LRT)로 주요 명소를 대부분 커버합니다"] },
            { label: "관광 밀도", values: ["도보 반경 안에 명소가 밀집해 있습니다", "명소보다는 카페·맛집 위주로 넓게 퍼져 있어요", "바닷가·야시장 등 명소가 적당한 간격으로 분산돼 있어요"] },
            { label: "부모님 동선", values: ["역에서 도보 5~10분 이내 명소가 많아 무난해요", "걷는 구간이 길어지기 쉬워 택시 이용을 고려해야 합니다", "역 인근으로 동선을 짜기가 비교적 쉬워요"] },
            { label: "근교 확장성", values: ["타오위안, 이란 방면", "일월담·칭징농장·허환산으로 가는 전초기지로 좋습니다", "타이난·컨딩·소류구를 묶는 남부투어가 가능해요"] },
          ],
        },
        { type: "figure", img: "assets/images/regions/taipei.webp", caption: "안개 낀 산 사이로 보이는 타이베이 시내 전경." },
        { type: "h2", text: "02 · 타이베이 — 고민 없는 기본값" },
        { type: "p", html: "타이베이는 대만 여행의 정답에 가깝습니다. 지하철(MRT) 노선이 시내 전역을 촘촘히 연결하고, 역에서 내려 조금만 걸으면 고궁박물원, 스린 야시장, 융캉제 같은 대표 명소에 닿아요. 부모님과 함께라면 이동 스트레스가 적다는 것만으로도 큰 장점입니다. 처음 대만을 찾는다면, 혹은 일정이 나흘 이하로 짧다면 타이베이 한 도시에만 집중하는 편이 오히려 여행을 편안하게 만들어요." },
        { type: "h2", text: "03 · 가오슝 — 타이베이 다음으로 가장 무난한 선택" },
        { type: "p", html: "가오슝은 한국으로 치면 부산에 가깝습니다. 서울(타이베이) 다음으로 부산(가오슝)을 찾는 것처럼, 대만 여행에서도 타이베이 다음 도시로 가장 많이 떠올리는 곳이에요. MRT와 경전철(LRT)이 주요 명소 대부분을 커버하고, 바닷가와 야시장이 가까이 있어 동선을 짜기 쉽습니다. 일정이 길다면 타이난, 컨딩, 소류구까지 묶어 남부 투어로 확장할 수 있는 거점이기도 해요." },
        { type: "h2", text: "04 · 타이중 — 미식·도시 감성은 좋지만 동선은 고려해야" },
        { type: "p", html: "타이중은 관광지보다는 '그냥 도시'에 가까운 매력이 있습니다. 미슐랭 맛집이 곳곳에 있고, 박물관·미술관·오페라하우스를 돌아보며 도시 감성을 느끼기 좋아요. 다만 버스는 배차나 정류장 위치가 여행자에게 낯설 수 있고, MRT는 정작 관광지를 비껴가는 구간이 많아 걷는 거리가 길어지기 쉽습니다. 대전과 자주 비교되는 이유이기도 해요 — 딱히 관광명소가 몰려 있진 않지만 맛집 투어로는 훌륭한 도시라는 점에서요. 부모님과 함께라면 택시나 차량 이동을 적극적으로 활용하는 게 좋습니다." },
        { type: "h2", text: "05 · 엄마와 함께라면, 이렇게 골라보세요" },
        {
          type: "tipList",
          items: [
            { mark: "첫", b: "첫 대만 여행 + 일정 4일 이하", desc: "타이베이 한 도시에 집중하는 게 가장 편합니다. 이동 스트레스가 없어야 부모님도 여행을 온전히 즐길 수 있어요." },
            { mark: "남", b: "타이베이 + 도시 하나 추가, 이동 편의가 우선", desc: "가오슝을 추천합니다. MRT·LRT로 동선이 짧고, 타이난·컨딩 등 근교 일정도 짜기 쉬워요." },
            { mark: "미", b: "미식 여행 + 며칠 여유, 도보는 어느 정도 괜찮음", desc: "타이중을 더해보세요. 미슐랭 맛집과 한적한 도시 분위기를 느낄 수 있지만, 택시 이동을 적극 활용하는 게 좋습니다." },
          ],
        },
        { type: "quote", text: "\"타이중이 대전이라면, 가오슝은 부산.\" — 여행자들 사이에서 자주 나오는 비유입니다. 목적에 맞게 고르면 후회가 없어요." },
        { type: "cta", title: "지도에서 도시별 맛집도 함께 준비하세요", desc: "타이베이·타이중·가오슝 맛집을 지역별로 지도에서 바로 확인해보세요.", btn: "지도 열기 →", href: "/map" },
        { type: "note", text: "이 글은 여행자들 사이에서 공유되는 각 도시의 대중교통 여건과 여행 경험을 바탕으로 정리했습니다. 실제 대중교통 노선과 운행 정보는 방문 전 현지 교통 앱으로 다시 확인하는 것을 추천해요." },
      ],
    },
    en: {
      pageTitle: "Taipei vs. Taichung vs. Kaohsiung — Best First City for a Trip with Mom · My Secret Taiwan Eats",
      metaDescription: "Which city is best for a first Taiwan trip with a parent? Comparing Taipei, Taichung, and Kaohsiung by transit difficulty, sightseeing density, and how walkable each is.",
      ogTitle: "Taipei vs. Taichung vs. Kaohsiung: Best First City for a Trip with Mom",
      eyebrow: "Taiwan Travel Guide · Choosing a City",
      title: "Taipei vs. Taichung vs. Kaohsiung: Best First City for a Trip with Mom",
      dek: "Transit options, sightseeing density, and — most importantly — how easy the walking is for a parent. We compared all three cities side by side to help pick a first Taiwan destination.",
      metaAuthor: "My Secret Taiwan Eats Editorial",
      metaTopic: "Taiwan Travel · City Comparison",
      intro: "Planning a first Taiwan trip with a parent makes choosing a city a bigger decision than usual. <strong>Taipei</strong> is the obvious default, but if you have a few extra days, the real question is whether to add <strong>Taichung</strong> or <strong>Kaohsiung</strong>. We compared all three on transit difficulty, sightseeing density, and — above all — how easy the walking routes are for a parent.",
      blocks: [
        { type: "h2", text: "01 · The Three Cities at a Glance" },
        {
          type: "compareTable",
          cities: ["Taipei", "Taichung", "Kaohsiung"],
          rows: [
            { label: "Transit difficulty", values: ["A dense MRT network means almost no long walks", "Relies heavily on buses; the MRT skips many tourist areas", "MRT plus a light rail (LRT) covers most major sights"] },
            { label: "Sightseeing density", values: ["Landmarks are packed within walking distance of each other", "Spread out and centered more on cafes and restaurants than sights", "Sights like the waterfront and night markets are spaced conveniently"] },
            { label: "Parent-friendly routes", values: ["Most sights are 5–10 min walk from a station", "Walking distances add up quickly; plan for taxis", "Relatively easy to build a route around stations"] },
            { label: "Day-trip potential", values: ["Taoyuan, Yilan area", "A good base for Sun Moon Lake, Cingjing Farm, Hehuanshan", "Can be combined with Tainan, Kenting, Xiaoliuqiu for a southern-Taiwan tour"] },
          ],
        },
        { type: "figure", img: "assets/images/regions/taipei.webp", caption: "The Taipei skyline seen through a mountain haze." },
        { type: "h2", text: "02 · Taipei — The Easy Default" },
        { type: "p", html: "Taipei is about as close to a sure bet as Taiwan travel gets. The MRT network blankets the city, and a short walk from any station gets you to major sights like the National Palace Museum, Shilin Night Market, or Yongkang Street. Traveling with a parent, low transit stress alone is a real advantage. If it's your first time in Taiwan, or your trip is four days or shorter, focusing on Taipei alone tends to make the whole trip more relaxed." },
        { type: "h2", text: "03 · Kaohsiung — The Easiest Second City" },
        { type: "p", html: "Kaohsiung plays a role similar to Busan in Korea — just as Busan is usually the second city travelers pick after Seoul, Kaohsiung is often the second city travelers add after Taipei. Its MRT and light rail (LRT) cover most major sights, and the waterfront and night markets are close together, making routes easy to plan. With more time, it's also a great base for extending south to Tainan, Kenting, and Xiaoliuqiu." },
        { type: "h2", text: "04 · Taichung — Great for Food and City Vibes, but Plan Around Transit" },
        { type: "p", html: "Taichung feels less like a tourist destination and more like \"just a city\" — in a good way. Michelin-listed restaurants are everywhere, and it's a great place to soak up museums, galleries, and an opera house at a relaxed pace. That said, bus schedules and stops can be confusing for visitors, and the MRT skips many of the areas travelers actually want to see, so walking distances add up. It's often compared to Daejeon in Korea for the same reason — not packed with landmarks, but excellent for a food-focused trip. Traveling with a parent, lean on taxis or a car rather than walking everything." },
        { type: "h2", text: "05 · Picking a City When You're Traveling with Mom" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "First trip to Taiwan, 4 days or fewer", desc: "Stick to Taipei alone. Keeping transit stress low is what lets a parent actually enjoy the trip." },
            { mark: "2", b: "Taipei plus one more city, prioritizing easy transit", desc: "Add Kaohsiung. MRT and LRT keep routes short, and it's easy to extend to Tainan or Kenting." },
            { mark: "3", b: "A food-focused trip with a few extra days, some walking is fine", desc: "Add Taichung. You'll get Michelin restaurants and a relaxed city feel — just lean on taxis to get around." },
          ],
        },
        { type: "quote", text: "\"If Taichung is Daejeon, Kaohsiung is Busan.\" — A comparison travelers bring up often. Pick based on what you're actually there for, and you won't regret it." },
        { type: "cta", title: "Find Restaurants in Each City on the Map", desc: "Browse restaurants in Taipei, Taichung, and Kaohsiung by region, right on the map.", btn: "Open Map →", href: "/map" },
        { type: "note", text: "This guide was put together from transit conditions and travel experiences commonly shared among travelers. Double-check current routes and schedules in a local transit app before you go." },
      ],
    },
  },
  "taipei-easycard-transport-guide": {
    heroImage: "assets/images/blog/taipei-taxi-night-market.jpg",
    ko: {
      pageTitle: "타이베이 이지카드로 충분할까 — 첫 여행 3박4일 교통 가이드 · 나만 알고 싶은 대만 맛집",
      metaDescription: "타이베이 첫 여행, 이지카드만으로 충분할까요? 신용카드 컨택리스 결제, 버스, 택시(우버)는 언제 타야 하는지까지 — 실제 여행자들의 경험을 바탕으로 정리했습니다.",
      ogTitle: "타이베이 첫 여행 3박4일, 이지카드만으로 충분할까?",
      eyebrow: "타이베이 여행 가이드 · 교통",
      title: "타이베이 첫 여행 3박4일, 이지카드만으로 충분할까?",
      dek: "이지카드 하나로 지하철·버스·편의점까지 다 되는지, 신용카드는 어디까지 되는지, 택시는 언제 타야 하는지 — 첫 타이베이 여행자들이 가장 많이 묻는 교통 고민을 정리했습니다.",
      metaAuthor: "나만 알고 싶은 대만 맛집 편집팀",
      metaTopic: "타이베이 · 교통 가이드",
      intro: "타이베이 여행을 준비하다 보면 꼭 한 번은 마주치는 질문이 있습니다. \"이지카드 하나로 충분할까? 신용카드도 되나? 택시는 언제 타야 하지?\" 대중교통이 촘촘한 타이베이는 사실 복잡하게 고민할 필요가 없는 도시예요. 실제 여행자들의 경험을 바탕으로 <strong>이지카드·신용카드·택시(우버)</strong>의 사용 범위를 한 번에 정리해봤습니다.",
      blocks: [
        { type: "h2", text: "01 · 이지카드 vs 신용카드, 어디까지 될까" },
        {
          type: "compareTable",
          cities: ["이지카드(EasyCard)", "신용카드(컨택리스)", "우버 / 택시"],
          rows: [
            { label: "지하철(MRT)", values: ["가능 — 공항철도 포함 전 노선", "가능 — 카드 뒷면에 컨택리스 결제 아이콘이 있어야 합니다", "필요할 때만 이용"] },
            { label: "버스", values: ["가능", "아직 지원 안 됨", "필요할 때만 이용"] },
            { label: "편의점 · 마트", values: ["가능 — 충전 잔액으로 바로 결제", "가능", "해당 없음"] },
            { label: "충전 · 준비", values: ["공항·지하철역·편의점에서 구매 및 충전", "기존에 쓰던 카드 그대로 사용, 별도 발급 불필요", "출국 전 앱 설치 및 카드 등록"] },
            { label: "첫 여행자 추천도", values: ["대중교통 위주라면 필수", "카드 결제를 선호한다면 보조 수단으로 좋습니다", "체력이 떨어지거나 짐이 많을 때, 혹은 편하게 이동하고 싶을 때 좋아요"] },
          ],
        },
        { type: "figure", img: "assets/images/blog/taipei-taxi-night-market.jpg", caption: "대만 택시는 전부 노란색이라 멀리서도 눈에 잘 띄어요." },
        { type: "h2", text: "02 · 유명 관광지는 거의 다 지하철·버스로 닿아요" },
        { type: "p", html: "타이베이는 유명 관광지 대부분이 MRT 노선과 버스 노선으로 커버됩니다. 고궁박물원, 스린 야시장, 융캉제, 시먼딩처럼 여행자들이 많이 찾는 코스는 이지카드 한 장이면 충분히 다닐 수 있어요. 구글 지도로 경로를 검색하면 지하철·버스 환승 정보는 물론 버스 하차 알림까지 챙겨주기 때문에, 초행길이라도 크게 헤맬 일이 없습니다." },
        { type: "h2", text: "03 · 택시(우버)는 언제 타야 할까" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "체력이 떨어졌을 때", desc: "하루 종일 걸어다닌 뒤 숙소로 돌아갈 때는, 무리해서 대중교통을 갈아타기보다 택시가 훨씬 편합니다." },
            { mark: "2", b: "쇼핑으로 짐이 많아질 때", desc: "양손 가득 짐을 들고 환승하기보다, 숙소까지 바로 이동하는 편이 나아요." },
            { mark: "3", b: "대중교통 환승이 애매할 때", desc: "노선이 꼬이거나 도보 이동이 길어지는 구간이라면, 택시가 시간과 체력을 아껴줍니다." },
            { mark: "4", b: "말이 잘 안 통하거나 깔끔한 차량을 원할 때", desc: "길거리에서 택시를 잡으면 목적지를 설명하기 애매하거나 차량 상태가 제각각일 수 있어요. 우버는 앱에 주소만 입력하면 되고 요금도 미리 확인할 수 있는 데다, 차량이 깨끗하고 기사님 서비스도 좋은 경우가 많아서 오히려 우버를 더 선호하는 여행자도 꽤 있습니다." },
          ],
        },
        { type: "h2", text: "04 · 3박4일, 실제로는 이렇게 다녀요" },
        { type: "p", html: "실제로 다녀온 여행자들의 후기를 보면 답은 비슷합니다. 3박4일 내내 지하철과 버스만으로 다녔다는 후기가 가장 많았고, 컨택리스 신용카드 한 장으로 대만에서 6일을 지내고 온 사례도 있었어요. 이지카드는 남은 잔액을 편의점에서 알뜰하게 쓰고 귀국하는 것도 흔한 방법입니다. 우버는 다들 미리 앱을 설치해두는 편인데, 실제로 타 본 여행자들 사이에서는 깨끗한 차량과 편한 결제 덕분에 만족스러웠다는 후기도 적지 않았어요." },
        { type: "quote", text: "\"걷는 게 괜찮으시다면 지하철로 움직이셔도 어지간하면 충분합니다.\" — 실제 타이베이를 다녀온 여행자들이 가장 많이 남긴 한마디입니다." },
        { type: "h2", text: "05 · 첫 여행자를 위한 체크리스트" },
        {
          type: "tipList",
          items: [
            { mark: "✓", b: "이지카드부터 챙기기", desc: "공항 도착 후 지하철역이나 편의점에서 바로 구매·충전할 수 있습니다. 지하철, 버스, 편의점까지 한 장으로 해결돼요." },
            { mark: "✓", b: "구글 지도 앱 미리 준비", desc: "노선 검색은 물론 버스 하차 알림까지 챙겨주니, 초행길에 특히 유용해요." },
            { mark: "✓", b: "우버 앱도 함께 준비하기", desc: "짐이 많거나 체력이 떨어졌을 때는 물론, 깔끔한 차량과 정찰 요금을 선호해서 길거리 택시 대신 우버를 즐겨 타는 여행자도 많아요. 미리 설치해두면 언제든 편하게 쓸 수 있습니다." },
            { mark: "✓", b: "컨택리스 신용카드 확인", desc: "카드 뒷면에 와이파이 모양(옆으로 누운) 아이콘이 있다면 지하철 결제가 가능합니다. 다만 버스는 아직 지원하지 않아요." },
          ],
        },
        { type: "cta", title: "타이베이 맛집도 지도에서 미리 찜해두세요", desc: "이지카드로 이동하면서 들르기 좋은 타이베이 맛집을 지도에서 확인해보세요.", btn: "지도 열기 →", href: "/map?region=taipei" },
        { type: "note", text: "이 글은 실제 타이베이를 다녀온 여행자들의 경험을 바탕으로 정리했습니다. 교통 요금과 결제 정책은 방문 전 대중교통 앱이나 공식 안내로 다시 확인하는 것을 추천해요." },
      ],
    },
    en: {
      pageTitle: "Is an EasyCard Enough for Taipei? A First-Timer's 4-Day Transportation Guide · My Secret Taiwan Eats",
      metaDescription: "Is an EasyCard alone enough for a first Taipei trip? When can you use a contactless credit card, and when should you actually take a taxi or Uber? Based on real traveler experiences.",
      ogTitle: "Taipei First Trip, 4 Days 3 Nights: Is an EasyCard Enough?",
      eyebrow: "Taipei Travel Guide · Transportation",
      title: "Taipei First Trip, 4 Days 3 Nights: Is an EasyCard Enough?",
      dek: "Whether one EasyCard covers the MRT, buses, and convenience stores, how far a contactless credit card gets you, and when to actually call a taxi — the transportation questions first-time Taipei travelers ask most.",
      metaAuthor: "My Secret Taiwan Eats Editorial",
      metaTopic: "Taipei · Transportation Guide",
      intro: "Planning a Taipei trip always brings up the same question: \"Is an EasyCard enough? Does my credit card work? When do I actually need a taxi?\" Taipei's transit network is dense enough that the answer is simpler than it sounds. Based on real traveler experiences, here's exactly how far an <strong>EasyCard, a contactless credit card, and Uber/taxis</strong> each get you.",
      blocks: [
        { type: "h2", text: "01 · EasyCard vs. Credit Card: What Each One Covers" },
        {
          type: "compareTable",
          cities: ["EasyCard", "Contactless Credit Card", "Uber / Taxi"],
          rows: [
            { label: "MRT", values: ["Yes — every line, including the Airport MRT", "Yes — your card needs the contactless payment icon on the back", "Use only when needed"] },
            { label: "Buses", values: ["Yes", "Not supported yet", "Use only when needed"] },
            { label: "Convenience stores & marts", values: ["Yes — pay straight from your card balance", "Yes", "N/A"] },
            { label: "Getting set up", values: ["Buy and top up at the airport, MRT stations, or convenience stores", "Just use the card you already have — no extra sign-up", "Install the app and register a card before you fly"] },
            { label: "Good for first-timers?", values: ["Essential if you're mostly using public transit", "A solid backup if you prefer paying by card", "Great when you're worn out, carrying a lot, or just want an easy ride"] },
          ],
        },
        { type: "figure", img: "assets/images/blog/taipei-taxi-night-market.jpg", caption: "Every taxi in Taiwan is yellow, so they're easy to spot from a distance." },
        { type: "h2", text: "02 · The MRT and Buses Already Cover Almost Every Famous Spot" },
        { type: "p", html: "Most of Taipei's well-known sights sit right on an MRT or bus line. Popular stops like the National Palace Museum, Shilin Night Market, Yongkang Street, and Ximending are all easily reachable with just an EasyCard. Google Maps handles transfers between MRT and bus routes and even tells you when to get off the bus, so it's hard to get lost even on your first day." },
        { type: "h2", text: "03 · When Should You Actually Take a Taxi?" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "When you're worn out", desc: "After a full day of walking, heading back to your hotel is a lot easier by taxi than by forcing another transit transfer." },
            { mark: "2", b: "When shopping has piled up your bags", desc: "Rather than transferring trains with your hands full, it's easier to go straight back to your hotel." },
            { mark: "3", b: "When the transit connection is awkward", desc: "If a route involves a confusing transfer or a long walk, a taxi saves both time and energy." },
            { mark: "4", b: "When you want an easier, cleaner ride", desc: "Flagging a street taxi can mean explaining your destination or getting whatever car happens to pull up. With Uber, you just enter the address, see the fare upfront, and the cars tend to be clean with friendly drivers — enough that plenty of travelers actually prefer it over hailing a regular taxi." },
          ],
        },
        { type: "h2", text: "04 · What a Real 4-Day Trip Actually Looks Like" },
        { type: "p", html: "Real traveler reviews tend to agree. Most people said they got through all four days on just the MRT and buses, and one traveler managed six days in Taiwan on a single contactless credit card. Spending down a leftover EasyCard balance at a convenience store before flying home is a common move too. Most travelers install the Uber app beforehand, and those who actually used it often mentioned how clean the cars were and how easy the payment was." },
        { type: "quote", text: "\"If you're fine with walking, the MRT alone is enough for almost everything.\" — The single most common piece of advice from travelers who've actually been to Taipei." },
        { type: "h2", text: "05 · A Checklist for First-Time Visitors" },
        {
          type: "tipList",
          items: [
            { mark: "✓", b: "Get an EasyCard first", desc: "You can buy and top one up right at the airport MRT station or a convenience store. One card covers the MRT, buses, and convenience stores." },
            { mark: "✓", b: "Set up Google Maps beforehand", desc: "It handles route search and bus-stop alerts, which is especially useful when you don't know the city yet." },
            { mark: "✓", b: "Set up Uber too", desc: "Beyond just tired-and-carrying-too-much situations, plenty of travelers prefer Uber's clean cars and upfront pricing over hailing a taxi off the street. Get it registered ahead of time so it's ready whenever you want it." },
            { mark: "✓", b: "Check for contactless on your credit card", desc: "If the back of your card has the sideways Wi-Fi-shaped icon, it works on the MRT — just not on buses yet." },
          ],
        },
        { type: "cta", title: "Bookmark Taipei Restaurants on the Map Too", desc: "Find Taipei restaurants worth stopping at while you get around on your EasyCard.", btn: "Open Map →", href: "/map?region=taipei" },
        { type: "note", text: "This guide was put together from the experiences of real Taipei travelers. Fares and payment policies can change, so double-check with a transit app or official source before you go." },
      ],
    },
  },
  "taipei-souvenir-gift-guide": {
    heroImage: "assets/images/blog/taiwan-pineapple-tart.jpg",
    ko: {
      pageTitle: "대만 여행 선물 추천 — 뻔한 간식 말고 뭘 사올까? · 나만 알고 싶은 대만 맛집",
      metaDescription: "펑리수, 누가크래커, 에그롤... 대만 선물은 늘 비슷하죠. 재방문객을 위한 추천부터 브랜드별 비교, 까르푸 가성비 팁까지 정리했습니다.",
      ogTitle: "대만 여행 선물 추천 — 뻔한 간식 말고 뭘 사올까?",
      eyebrow: "타이베이 여행 가이드 · 선물",
      title: "대만 여행 선물 추천 — 뻔한 간식 말고 뭘 사올까?",
      dek: "회사 선물부터 재방문객을 위한 신상 간식까지 — 여행자들이 실제로 사 온 대만 선물과 브랜드별 비교, 가성비 팁을 한 번에 정리했습니다.",
      metaAuthor: "나만 알고 싶은 대만 맛집 편집팀",
      metaTopic: "타이베이 · 선물 가이드",
      intro: "대만 여행 선물 하면 펑리수, 누가크래커, 에그롤, 우롱차가 먼저 떠오릅니다. 다 좋은 선택이지만, 여러 번 다녀온 여행자라면 슬슬 새로운 선물이 궁금해지기 마련이에요. 실제 여행자들이 사 온 선물 후기를 바탕으로, 무난한 '국룰' 선물부터 브랜드별 비교, 예산에 맞게 고르는 팁까지 정리해봤어요.",
      blocks: [
        { type: "h2", text: "01 · 실패 없는 '국룰' 선물 리스트" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "펑리수(鳳梨酥)", desc: "대만 선물의 대명사입니다. 브랜드마다 맛과 가격 차이가 있어서, 이름 있는 브랜드로 사면 실패할 일이 거의 없어요." },
            { mark: "2", b: "누가크래커(牛軋餅)", desc: "회사에 가볍게 돌릴 선물로 가장 무난하다는 평이 많습니다. 다만 브랜드에 따라 맛 차이가 꽤 커요." },
            { mark: "3", b: "에그롤(蛋捲)", desc: "바삭한 식감 덕분에 호불호가 적은 편입니다. 크림이 들어간 제품도 있어서 맛을 다양하게 골라볼 수 있어요." },
            { mark: "4", b: "우롱차 · 대만 홍차", desc: "차를 즐기는 분에게 특히 좋습니다. 부피가 작아 캐리어에 넣기도 편해요." },
            { mark: "5", b: "금문 고량주", desc: "간식은 아니지만 받는 사람마다 크게 반가워한다는 후기가 많습니다. 도수가 높은 편이라 술을 즐기는 분께 추천할 만해요." },
          ],
        },
        { type: "figure", img: "assets/images/blog/taiwan-pineapple-tart.jpg", caption: "한 입 베어 문 펑리수와 따뜻한 차 한 잔 — 대만 선물의 정석 조합." },
        { type: "h2", text: "02 · 재방문객이라면, 이런 것도 찾아보세요" },
        { type: "p", html: "펑리수·누가크래커는 이제 익숙하다면, 크림이 들어간 에그롤처럼 조금 다른 버전을 찾아보는 것도 방법입니다. 맛을 여러 가지로 시식해보고 고를 수 있는 매장도 있고, 포장이 깔끔해서 선물용으로도 무난하다는 후기가 많아요." },
        { type: "h2", text: "03 · 누가크래커, 브랜드마다 이렇게 다릅니다" },
        {
          type: "compareTable",
          cities: ["전문 브랜드(세인트피터 등)", "까르푸 등 마트", "스위덤"],
          rows: [
            { label: "가격대", values: ["다소 비싼 편", "가장 저렴", "중간 — 만원 안팎"] },
            { label: "맛 평가", values: ["꾸준히 좋은 평, 다만 가격이 계속 오르는 추세", "브랜드에 따라 편차가 커서 호불호가 갈립니다", "가격 대비 맛이 좋다는 후기가 많아요"] },
            { label: "추천 상황", values: ["정성껏 챙기고 싶은 선물일 때", "가볍게 인사치레만 할 때", "가성비 좋은 선물을 찾을 때"] },
          ],
        },
        { type: "h2", text: "04 · 예산과 상황에 맞게 고르는 법" },
        {
          type: "tipList",
          items: [
            { mark: "✓", b: "제대로 챙기고 싶은 선물이라면", desc: "전문 브랜드 매장에서 사는 게 안전합니다. 가격은 더 나가지만 맛과 포장 모두 검증된 편이에요." },
            { mark: "✓", b: "가볍게 여러 개 돌릴 선물이라면", desc: "까르푸 같은 마트에서 사도 충분하다는 의견이 많습니다. 다만 마트 자체 누가크래커는 호불호가 갈린다는 후기가 있으니, 브랜드를 확인하고 고르는 게 좋아요." },
            { mark: "✓", b: "최근 대만 물가가 많이 올랐다는 점도 참고하기", desc: "오랜만에 방문하는 여행자라면 예전 가격을 생각하고 갔다가 놀랄 수 있습니다. 예산을 조금 여유 있게 잡아두는 걸 추천해요." },
          ],
        },
        { type: "quote", text: "\"까르푸 누가는 하나 먹고 다 버렸어요, 선물로 주면 욕먹을지도... 스위덤은 가격도 착하고 맛있어요.\" — 여러 브랜드를 직접 먹어본 여행자가 남긴 비교입니다." },
        { type: "cta", title: "지도에서 마트·간식 스팟도 확인해보세요", desc: "선물 쇼핑하기 좋은 마트와 간식 매장을 지도에서 바로 찾아보세요.", btn: "지도 열기 →", href: "/map?region=taipei&cat=mart" },
        { type: "note", text: "이 글은 여행자들이 실제로 사 온 선물 후기를 바탕으로 정리했습니다. 브랜드별 가격과 맛 평가는 개인차가 있을 수 있으니 참고용으로 봐주세요." },
      ],
    },
    en: {
      pageTitle: "Taiwan Souvenir Guide: What to Bring Home Besides the Usual Snacks · My Secret Taiwan Eats",
      metaDescription: "Pineapple cake, nougat crackers, egg rolls... Taiwan souvenirs can get repetitive. Here's what repeat visitors actually buy, a brand comparison, and budget tips for shopping at Carrefour.",
      ogTitle: "Taiwan Souvenir Guide: What to Bring Home Besides the Usual Snacks",
      eyebrow: "Taipei Travel Guide · Souvenirs",
      title: "Taiwan Souvenir Guide: What to Bring Home Besides the Usual Snacks",
      dek: "From office gifts to something new for repeat visitors — real traveler picks, a brand-by-brand comparison, and budget tips, all in one place.",
      metaAuthor: "My Secret Taiwan Eats Editorial",
      metaTopic: "Taipei · Souvenir Guide",
      intro: "Ask anyone what to bring back from Taiwan and you'll hear the same four things: pineapple cake, nougat crackers, egg rolls, oolong tea. They're all solid choices, but if you've been to Taiwan more than once, you're probably ready for something new. Based on real traveler reviews, here's the reliable classic list, a brand comparison, and how to choose based on your budget.",
      blocks: [
        { type: "h2", text: "01 · The Reliable Classics" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "Pineapple Cake (鳳梨酥)", desc: "The single most iconic Taiwan souvenir. Quality varies a lot by brand, so sticking with a well-known one is nearly foolproof." },
            { mark: "2", b: "Nougat Crackers (牛軋餅)", desc: "Often called the safest pick for handing out at the office. The taste differs quite a bit between brands, so which one you buy matters." },
            { mark: "3", b: "Egg Rolls (蛋捲)", desc: "The crunchy texture makes these an easy crowd-pleaser. Some shops offer cream-filled versions for extra variety." },
            { mark: "4", b: "Oolong or Taiwanese Black Tea", desc: "Great for anyone who drinks tea. Compact and easy to pack too." },
            { mark: "5", b: "Kinmen Kaoliang Liquor", desc: "Not a snack, but travelers say it gets one of the biggest reactions of any gift. Worth it if the recipient drinks." },
          ],
        },
        { type: "figure", img: "assets/images/blog/taiwan-pineapple-tart.jpg", caption: "A bitten pineapple cake and a cup of tea — Taiwan's classic pairing." },
        { type: "h2", text: "02 · If You've Been Before, Look For This Too" },
        { type: "p", html: "If pineapple cake and nougat crackers already feel familiar, cream-filled egg rolls are worth a try for something a little different. Some shops let you sample a range of flavors before you buy, and the packaging tends to be clean enough for gifting." },
        { type: "h2", text: "03 · Nougat Crackers: How the Brands Actually Compare" },
        {
          type: "compareTable",
          cities: ["Specialty brands (e.g. St. Peter)", "Supermarkets like Carrefour", "Sweetum"],
          rows: [
            { label: "Price", values: ["On the pricier side", "The cheapest option", "Mid-range — roughly $7–8 USD"] },
            { label: "Taste", values: ["Consistently good, though prices keep climbing", "Varies a lot by brand — hit or miss", "Often praised as good value for the price"] },
            { label: "Best for", values: ["A gift you want to get right", "A quick, casual gift for several people", "Good taste without the premium price tag"] },
          ],
        },
        { type: "h2", text: "04 · Choosing by Budget and Occasion" },
        {
          type: "tipList",
          items: [
            { mark: "✓", b: "For a gift you want to nail", desc: "Buy from a specialty brand store. It costs more, but both the taste and packaging are proven." },
            { mark: "✓", b: "For handing out several casual gifts", desc: "A supermarket like Carrefour works fine for most people. Just know that the store's own-brand nougat gets mixed reviews, so it's worth checking which brand you're grabbing." },
            { mark: "✓", b: "Keep in mind that prices in Taiwan have risen a lot", desc: "If it's been a while since your last visit, budget a bit more than you remember — prices have gone up noticeably." },
          ],
        },
        { type: "quote", text: "\"I ate one piece of the Carrefour nougat and threw the rest away — giving that as a gift might get you some complaints. Sweetum was actually good, and reasonably priced too.\" — One traveler's brand-by-brand verdict after trying several." },
        { type: "cta", title: "Find Mart and Snack Spots on the Map", desc: "Look up supermarkets and snack shops that are good for souvenir shopping, right on the map.", btn: "Open Map →", href: "/map?region=taipei&cat=mart" },
        { type: "note", text: "This guide was put together from real travelers' souvenir shopping experiences. Brand-by-brand pricing and taste are a matter of personal preference, so take it as a starting point." },
      ],
    },
  },
  "taipei-overnight-red-eye-flight-last-day": {
    heroImage: "assets/images/blog/taipei-chiang-kai-shek-hall-night.jpg",
    ko: {
      pageTitle: "타이베이 무박 일정 가이드 — 숙박 없이 새벽 비행기 타기 · 나만 알고 싶은 대만 맛집",
      metaDescription: "마지막 날 숙소를 잡지 않고 새벽 비행기를 타는 '무박' 일정, 가능할까요? 실제로 그렇게 다녀온 여행자들의 경험을 바탕으로 장단점과 시간 활용법을 정리했습니다.",
      ogTitle: "타이베이 마지막 날, 숙박 없이 새벽 비행기 타도 될까?",
      eyebrow: "타이베이 여행 가이드 · 일정 팁",
      title: "타이베이 마지막 날, 숙박 없이 새벽 비행기 타도 될까?",
      dek: "체크아웃 후 하루를 통으로 놀고 바로 공항으로 — 숙박비를 아끼는 '무박' 일정, 실제로 해본 여행자들의 경험과 시간 활용법을 정리했습니다.",
      metaAuthor: "나만 알고 싶은 대만 맛집 편집팀",
      metaTopic: "타이베이 · 일정 가이드",
      intro: "타이베이 여행 마지막 날, 비행기가 새벽 2~3시라면 고민이 생깁니다. 하루 더 숙박을 잡을지, 아니면 체크아웃 후 그대로 놀다가 공항으로 직행할지. 실제로 '무박'으로 다녀온 여행자들의 경험을 바탕으로 장단점과 시간 활용법을 정리해봤어요.",
      blocks: [
        { type: "h2", text: "01 · 무박, 해볼 만할까?" },
        { type: "p", html: "결론부터 말하면 '사바사'입니다. 체력이 좋다면 충분히 가능하고, 숙박비도 아낄 수 있어서 실제로 시도하는 여행자가 많아요. 반면 어린 자녀나 어르신과 함께라면, 혹은 귀국 다음 날 바로 출근해야 한다면 무리하지 않는 편이 낫다는 의견도 많습니다." },
        { type: "h2", text: "02 · 실제로 이렇게 시간을 보내요" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "체크아웃 후 짐 보관", desc: "호텔이나 근처 짐 보관 서비스에 맡기고 몸만 가볍게 움직입니다. 대부분의 숙소에서 체크아웃 이후에도 짐을 맡아줘요." },
            { mark: "2", b: "저녁까지는 평소처럼 관광·쇼핑", desc: "레이트 체크아웃이 가능하면 오후 늦게 일정을 시작하는 것도 방법입니다. 마지막 날이라고 특별히 다를 것 없이 자유롭게 시간을 보내요." },
            { mark: "3", b: "샤워되는 마사지숍에서 마무리", desc: "마사지를 받고 그 자리에서 씻고 나오면 한결 개운합니다. 짐 정리와 체력 회복을 동시에 해결할 수 있어요." },
            { mark: "4", b: "공항 이동은 밤 10시~11시 전후", desc: "공항철도나 국광버스(1819)를 타고 여유 있게 이동합니다. 타이베이 메인역에서 버스를 타면 큰 정체 없이 도착해요." },
            { mark: "5", b: "공항 도착 후 무료 샤워장·라운지 활용", desc: "타오위안 공항에는 무료 샤워 시설이 있어서, 탑승 전 한 번 더 씻고 정비할 수 있습니다. 라운지 이용이 가능하다면 그곳에서 쉬다 타는 것도 좋아요." },
          ],
        },
        { type: "figure", img: "assets/images/blog/taipei-chiang-kai-shek-hall-night.jpg", caption: "야간 조명이 켜진 중정기념당(자유광장) — 마지막 밤 산책 코스로도 좋아요." },
        { type: "h2", text: "03 · 그래도 하루 더 자는 게 나은 경우" },
        {
          type: "tipList",
          items: [
            { mark: "✓", b: "어린 자녀나 어르신과 함께라면", desc: "체력 부담이 커서, 짧게라도 호스텔 1박이나 '0.5박'으로 눈을 붙이고 가는 게 안전합니다." },
            { mark: "✓", b: "귀국 다음 날 바로 출근·등교한다면", desc: "무박으로 다녀오면 컨디션 난이도가 꽤 높아요. 도착 후 일정이 있다면 숙박을 잡는 편이 낫습니다." },
            { mark: "✓", b: "숙박비를 아예 포기하기 어렵다면", desc: "굳이 호텔이 아니어도 됩니다. 호스텔 1박만 추가해도 짧게 눈을 붙이고 짐도 여유 있게 정리할 수 있어요." },
          ],
        },
        { type: "quote", text: "\"이왕 가신 거 후회 없이 놀아보세요. 이렇게 놀 수 있는 기회가 흔치는 않다고 생각해요.\" — 무박 일정을 응원하는 여행자들의 댓글이에요." },
        { type: "cta", title: "지도에서 마지막 날 코스도 짜보세요", desc: "숙소·마사지숍·야시장까지, 마지막 날 동선을 지도에서 한눈에 확인해보세요.", btn: "지도 열기 →", href: "/map?region=taipei" },
        { type: "note", text: "이 글은 여행자들이 실제로 겪은 무박 일정 경험을 바탕으로 정리했습니다. 체력과 컨디션은 사람마다 다르니, 무리하지 않는 선에서 참고해 주세요." },
      ],
    },
    en: {
      pageTitle: "Taipei Red-Eye Flight Guide: Skipping the Last Hotel Night · My Secret Taiwan Eats",
      metaDescription: "Can you skip booking a hotel on your last night and catch a 2-3am flight instead? Based on real traveler experiences, here are the pros, cons, and how to spend the time.",
      ogTitle: "Taipei Last Day: Can You Skip the Hotel and Catch a Red-Eye Flight?",
      eyebrow: "Taipei Travel Guide · Itinerary Tips",
      title: "Taipei Last Day: Can You Skip the Hotel and Catch a Red-Eye Flight?",
      dek: "Check out, spend the whole day out, and head straight to the airport — real traveler experiences on this hotel-skipping itinerary and how to make the most of the time.",
      metaAuthor: "My Secret Taiwan Eats Editorial",
      metaTopic: "Taipei · Itinerary Guide",
      intro: "If your flight out of Taipei leaves at 2 or 3am, you're faced with a choice: book one more night, or check out and just keep going until it's time for the airport. Based on real travelers who've actually done the latter, here's a rundown of the pros, cons, and how to spend the time.",
      blocks: [
        { type: "h2", text: "01 · Is Skipping the Hotel Actually Worth It?" },
        { type: "p", html: "The short answer: it depends on you. If your stamina is up for it, it's a completely viable way to save on a hotel night, and plenty of travelers do it. On the other hand, if you're traveling with young kids or older family members, or you have to go straight to work the next day, most people say it's not worth pushing it." },
        { type: "h2", text: "02 · How Travelers Actually Spend the Time" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "Check out and store your luggage", desc: "Most hotels will hold your bags after checkout, so you can move around freely without them." },
            { mark: "2", b: "Keep sightseeing or shopping like normal", desc: "If a late checkout is available, starting the day later is another option. There's no need to treat it differently just because it's your last day." },
            { mark: "3", b: "Finish up at a massage shop with showers", desc: "Getting a massage and showering on-site leaves you feeling refreshed. It doubles as a chance to repack and recover some energy." },
            { mark: "4", b: "Head to the airport around 10-11pm", desc: "Take the Airport MRT or the Kuo-Kuang bus (route 1819) with plenty of time to spare. From Taipei Main Station, the bus gets you there without much traffic." },
            { mark: "5", b: "Use the free showers or a lounge at the airport", desc: "Taoyuan Airport has free shower facilities, so you can freshen up again right before boarding. If you have lounge access, resting there before your flight helps too." },
          ],
        },
        { type: "figure", img: "assets/images/blog/taipei-chiang-kai-shek-hall-night.jpg", caption: "Chiang Kai-shek Memorial Hall lit up at night — a good spot for one last evening walk." },
        { type: "h2", text: "03 · When It's Better to Book One More Night" },
        {
          type: "tipList",
          items: [
            { mark: "✓", b: "Traveling with young kids or older family members", desc: "The physical toll adds up fast. A short hostel stay or a half-night booking is the safer call." },
            { mark: "✓", b: "You have to work or go to school the day you land", desc: "Skipping the hotel makes for a genuinely tough recovery. If you have plans right after landing, book a room instead." },
            { mark: "✓", b: "You'd rather not give up sleep entirely", desc: "It doesn't have to be a hotel — even one hostel night gives you a chance to rest and repack without rushing." },
          ],
        },
        { type: "quote", text: "\"Since you're already there, might as well enjoy it without regrets. Chances to stay out until your flight like that don't come around often.\" — from travelers cheering on a no-hotel last day." },
        { type: "cta", title: "Plan Your Last Day on the Map Too", desc: "Find hotels, massage shops, and night markets for your last-day route, right on the map.", btn: "Open Map →", href: "/map?region=taipei" },
        { type: "note", text: "This guide was put together from real travelers' experiences skipping the last hotel night. Everyone's stamina is different, so use this as a reference and don't push yourself too hard." },
      ],
    },
  },
  "taipei-liquid-checked-baggage-guide": {
    heroImage: "assets/images/blog/taiwan-pineapple-tart.jpg",
    ko: {
      pageTitle: "대만 간식·술 기내 반입 규정 — 젤리·푸딩부터 고량주까지 · 나만 알고 싶은 대만 맛집",
      metaDescription: "대만에서 산 젤리·푸딩 간식과 술, 기내 반입이 될지 위탁수하물로 부쳐야 할지 헷갈리시나요? 액체·젤류 반입 기준, 주류 위탁 규정, 한국 입국 시 면세 한도까지 정리했습니다.",
      ogTitle: "대만 간식·술, 기내 반입 될까 위탁수하물로 부쳐야 할까",
      eyebrow: "타이베이 여행 가이드 · 쇼핑·수하물",
      title: "대만 간식·술, 기내 반입 될까 위탁수하물로 부쳐야 할까",
      dek: "닥터큐 젤리, 통일푸딩처럼 말랑한 간식도 '액체'로 분류될 수 있다는 사실, 알고 계셨나요? 술을 살 때 챙겨야 할 위탁수하물 규정과 한국 입국 면세 한도까지 한 번에 정리했습니다.",
      metaAuthor: "나만 알고 싶은 대만 맛집 편집팀",
      metaTopic: "타이베이 · 쇼핑 가이드",
      intro: "대만 마트에서 젤리나 푸딩 같은 말랑한 간식을 왕창 사놓고, 공항에서야 '이거 액체류 아닌가?' 싶어진 경험 없으신가요. 여기에 술까지 산다면 위탁수하물 규정과 한국 입국 시 면세 한도까지 함께 고려해야 해요. 헷갈리기 쉬운 <strong>기내 반입 vs 위탁수하물</strong> 기준을 정리해봤습니다.",
      blocks: [
        { type: "h2", text: "01 · 젤리·푸딩도 '액체'로 취급됩니다" },
        { type: "p", html: "국제선 보안검색에서는 순수한 물이나 음료뿐 아니라 젤리, 푸딩, 잼, 크림처럼 흐르거나 짜서 먹는 형태의 식품도 액체·젤류로 분류합니다. 닥터큐 젤리, 통일푸딩처럼 대만 마트에서 인기 있는 간식도 예외가 아니에요. 이런 제품을 기내 휴대용 가방에 넣으려면 용기 하나당 100ml 이하여야 하고, 여러 개를 합쳐도 1L 이하 투명 지퍼백 한 개에 다 들어가야 합니다. 용기 자체가 100ml를 넘으면 안에 든 양이 적어도 반입이 불가능해요." },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "젤리·푸딩류", desc: "닥터큐, 통일푸딩 등은 액체·젤류로 분류됩니다. 여러 개 사셨다면 위탁수하물에 넣는 편이 안전해요." },
            { mark: "2", b: "잼·소스·꿀류", desc: "펑리수는 고체라 문제 없지만, 잼이나 소스류 선물은 액체 기준이 적용됩니다." },
            { mark: "3", b: "화장품 샘플·마스크팩 에센스", desc: "여행 중 산 스킨케어 제품도 100ml 기준을 적용받아요." },
            { mark: "4", b: "위탁수하물은 이 규정에서 자유롭습니다", desc: "액체·젤류 자체는 위탁 가방에 넣으면 용량 제한 없이 부칠 수 있어요. 다만 술은 아래 규정을 따로 확인해야 합니다." },
          ],
        },
        { type: "h2", text: "02 · 술은 도수에 따라 위탁 가능 여부가 갈려요" },
        {
          type: "compareTable",
          cities: ["24도 이하", "24도 초과 ~ 70도 이하", "70도 초과"],
          rows: [
            { label: "위탁수하물 반입", values: ["제한 없이 가능", "1인당 5L까지 가능", "운송 자체가 금지됩니다"] },
            { label: "해당 주류 예시", values: ["대부분의 맥주·와인·약주", "고량주, 일부 위스키·백주(53~58도 안팎)", "일부 고도수 스피릿"] },
          ],
        },
        { type: "p", html: "금문 고량주처럼 인기 있는 선물용 술은 보통 53~58도라 '24도 초과 70도 이하' 구간에 들어갑니다. 1인당 5L까지 위탁 가능하니 일반적인 여행 구매량이라면 크게 걱정하지 않아도 돼요. 다만 항공사별로 세부 규정이 다를 수 있으니, 대량으로 구매했다면 출발 전 항공사 홈페이지에서 한 번 더 확인하는 걸 추천합니다." },
        { type: "h2", text: "03 · 한국 입국할 때, 주류 면세 한도는 얼마나 될까" },
        { type: "p", html: "2025년 3월 21일부터 한국 입국 시 주류 면세 기준이 바뀌었습니다. 예전에는 '2병까지'라는 병 수 제한이 있었지만, 지금은 병 개수와 상관없이 <strong>합계 용량 2L 이하, 총 가격 미화 400달러 이하</strong>라는 두 조건만 지키면 면세를 받을 수 있어요. 이 기준을 넘으면 초과분이 아니라 해당 주류 전체 금액에 세금이 부과될 수 있으니, 여러 병을 나눠 살 계획이라면 합계 용량과 가격을 미리 계산해두는 게 안전합니다." },
        {
          type: "tipList",
          items: [
            { mark: "✓", b: "젤리·푸딩은 위탁 가방에", desc: "여러 개 구매했다면 캐리어 안에 넣어 부치는 게 가장 깔끔합니다." },
            { mark: "✓", b: "면세점 구매 주류는 봉인 유지", desc: "출국장 면세점에서 산 술은 밀봉 봉투(탬퍼 백)와 영수증을 그대로 유지하면 기내 반입이 가능합니다. 환승편이 있다면 환승 공항 규정도 함께 확인하세요." },
            { mark: "✓", b: "도수·용량 미리 확인", desc: "고량주 등은 병에 적힌 알코올 도수(%)를 확인해 5L 한도 안에 들어오는지 계산해두세요." },
            { mark: "✓", b: "총액 400달러 넘으면 자진신고", desc: "한도를 넘겼다면 입국장에서 자진신고하면 세액 일부를 감면받을 수 있습니다." },
          ],
        },
        { type: "cta", title: "지도에서 마트·주류 매장도 확인해보세요", desc: "간식·술 쇼핑하기 좋은 마트와 주류 매장을 지도에서 바로 찾아보세요.", btn: "지도 열기 →", href: "/map?region=taipei&cat=mart" },
        { type: "note", text: "이 글은 2025년 3월 개정된 한국 관세청 기준과 일반적인 국제선 보안검색 규정을 바탕으로 정리했습니다. 항공사·환승 공항에 따라 세부 규정이 다를 수 있고, 관세 기준도 이후 바뀔 수 있으니 출발 전 관세청 홈페이지와 항공사 안내로 다시 확인하시길 권합니다." },
      ],
    },
    en: {
      pageTitle: "Taiwan Snacks & Liquor: Carry-On or Checked Baggage? · My Secret Taiwan Eats",
      metaDescription: "Not sure if jelly cups, pudding snacks, or liquor from Taiwan need to go in checked baggage? Here's how the liquid/gel rule applies, alcohol checked-baggage limits, and Korea's duty-free allowance.",
      ogTitle: "Taiwan Snacks and Liquor: Carry-On or Checked Baggage?",
      eyebrow: "Taipei Travel Guide · Shopping & Baggage",
      title: "Taiwan Snacks and Liquor: Carry-On or Checked Baggage?",
      dek: "Did you know jelly cups and pudding snacks can count as \"liquids\" at airport security? Here's what to know about checked-baggage alcohol limits and Korea's duty-free allowance.",
      metaAuthor: "My Secret Taiwan Eats Editorial",
      metaTopic: "Taipei · Shopping Guide",
      intro: "Ever stocked up on jelly cups or pudding snacks at a Taiwan supermarket, then wondered at the airport whether they count as liquids? Add alcohol to the mix and you're also dealing with checked-baggage rules and Korea's duty-free allowance. Here's a clear rundown of what goes in your <strong>carry-on versus checked baggage</strong>.",
      blocks: [
        { type: "h2", text: "01 · Yes, Jelly and Pudding Count as \"Liquids\"" },
        { type: "p", html: "International security screening doesn't just apply to water and drinks — it covers anything that flows, spreads, or squeezes out, including jelly cups, pudding, jam, and cream. Popular Taiwan supermarket snacks like Dr. Q jelly cups or Uni-President pudding are no exception. To carry these on board, each container needs to hold 100ml or less, and all of them together need to fit in a single 1L transparent resealable bag. Even a container that's mostly empty gets rejected if the container itself is over 100ml." },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "Jelly cups and pudding", desc: "Dr. Q jelly and Uni-President pudding count as liquids/gels. If you bought several, checked baggage is the safer bet." },
            { mark: "2", b: "Jam, sauces, and honey", desc: "Pineapple cake is solid and fine, but jam or sauce gifts fall under the liquid rule." },
            { mark: "3", b: "Cosmetic samples and sheet mask essence", desc: "Skincare products you pick up while traveling are also subject to the 100ml rule." },
            { mark: "4", b: "Checked baggage isn't subject to this rule", desc: "Liquids and gels themselves have no volume limit once they're in checked baggage. Alcohol is the one exception — see below." },
          ],
        },
        { type: "h2", text: "02 · Alcohol Limits Depend on Proof, Not Just Volume" },
        {
          type: "compareTable",
          cities: ["24% ABV or less", "Over 24% up to 70% ABV", "Over 70% ABV"],
          rows: [
            { label: "Checked baggage", values: ["No limit", "Up to 5L per passenger", "Not allowed to fly at all"] },
            { label: "Typical examples", values: ["Most beer, wine, and light liquors", "Kaoliang liquor, some whiskies and baijiu (roughly 53-58%)", "Some high-proof spirits"] },
          ],
        },
        { type: "p", html: "Kinmen Kaoliang, a popular gift liquor, usually runs 53-58% ABV, landing it in the \"over 24%, up to 70%\" bracket — good for up to 5L per passenger in checked baggage, more than enough for typical travel-sized purchases. Rules can vary slightly by airline, though, so if you're buying in bulk, double-check with your airline before you fly." },
        { type: "h2", text: "03 · Korea's Duty-Free Alcohol Allowance" },
        { type: "p", html: "Korea's duty-free alcohol rule changed on March 21, 2025. The old \"up to 2 bottles\" limit is gone — now it's just two conditions: <strong>2 liters total volume or less, and $400 total value or less</strong>, regardless of how many bottles that is. Go over either limit, and tax can apply to the full value of that alcohol, not just the excess. If you're splitting your purchase across a few bottles, add up the total volume and price beforehand to stay safe." },
        {
          type: "tipList",
          items: [
            { mark: "✓", b: "Pack jelly and pudding in checked baggage", desc: "If you bought more than one, putting them in your suitcase is the simplest fix." },
            { mark: "✓", b: "Keep duty-free alcohol sealed", desc: "Liquor bought at an airside duty-free shop can go in your carry-on if it stays in its sealed tamper-evident bag with the receipt. If you're connecting through another airport, check that airport's rules too." },
            { mark: "✓", b: "Check the ABV and volume", desc: "For Kaoliang and similar spirits, check the printed alcohol percentage and make sure your total stays within the 5L limit." },
            { mark: "✓", b: "Declare if you're over $400", desc: "Going over the limit? Declaring it voluntarily on arrival can reduce the tax owed." },
          ],
        },
        { type: "cta", title: "Find Marts and Liquor Shops on the Map", desc: "Look up marts and liquor shops that are good for snack and alcohol shopping, right on the map.", btn: "Open Map →", href: "/map?region=taipei&cat=mart" },
        { type: "note", text: "This guide is based on Korea Customs Service rules effective March 2025 and general international security screening standards. Details can vary by airline and connecting airport, and customs rules may change again, so double-check with the Korea Customs Service and your airline before you fly." },
      ],
    },
  },
  "taipei-xiangde-peking-duck-half-day-course": {
    heroImage: "assets/images/regions/taipei.webp",
    ko: {
      pageTitle: "샹덕 베이징덕 먹고 어디 갈까 — 중샤오둔화 반나절 코스 · 나만 알고 싶은 대만 맛집",
      metaDescription: "예약 필수인 베이징덕 맛집 샹덕(享鴨)에서 식사하고 근처를 가볍게 돌아보고 싶다면. 중샤오둔화역 주변 쇼핑가, 다안삼림공원, 쑹산문창원구까지 묶은 반나절 코스를 정리했습니다.",
      ogTitle: "베이징덕 맛집 샹덕(享鴨) 먹고 어디 갈까 — 중샤오둔화 반나절 코스",
      eyebrow: "타이베이 여행 가이드 · 맛집 코스",
      title: "베이징덕 맛집 샹덕(享鴨) 먹고 어디 갈까 — 중샤오둔화 반나절 코스",
      dek: "통짜 오리를 테이블에서 직접 썰어주는 퍼포먼스로 유명한 베이징덕 전문점 샹덕. 식사 전후로 가볍게 돌아볼 수 있는 주변 코스를 짜봤습니다.",
      metaAuthor: "나만 알고 싶은 대만 맛집 편집팀",
      metaTopic: "타이베이 · 맛집 코스",
      intro: "베이징덕 맛집 샹덕(享鴨, Xiang Duck)은 예약을 잡기가 쉽지 않을 만큼 인기 있는 곳이에요. 대표 지점은 <strong>중샤오둔화역</strong> 인근, 다안구와 송산구가 맞닿는 중샤오동로 4단에 있습니다. 모처럼 예약까지 잡고 찾아가는 만큼, 식사 전후로 가볍게 돌아볼 수 있는 반나절 코스를 함께 정리해봤어요.",
      blocks: [
        { type: "h2", text: "01 · 샹덕(享鴨), 예약 전 체크리스트" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "예약은 필수입니다", desc: "테이블에서 통오리를 직접 썰어주는 퍼포먼스로 유명해 현장 대기보다는 사전 예약이 기본입니다." },
            { mark: "2", b: "브레이크타임 확인하기", desc: "지점에 따라 오후 시간대에 브레이크타임이 있을 수 있어요. 예약할 때 영업시간을 함께 확인하는 게 안전합니다." },
            { mark: "3", b: "오리 한 마리 기준 인원수 확인", desc: "통오리 한 마리는 보통 2~3인이 함께 먹기 좋은 양이에요. 일행 수에 맞춰 주문 구성을 미리 물어보세요." },
          ],
        },
        { type: "h2", text: "02 · 식사 전 — 중샤오둔화 쇼핑가" },
        { type: "p", html: "중샤오둔화역 주변은 SOGO 백화점 푸싱점을 중심으로 골목마다 편집숍과 부티크가 모여 있는 쇼핑가입니다. 예약 시간보다 일찍 도착했다면 이 일대를 걸으며 시간을 보내기 좋아요. 대형 백화점부터 작은 브랜드 매장까지 다양해서, 날씨와 상관없이 돌아보기 편한 것도 장점입니다." },
        { type: "h2", text: "03 · 식사 후 — 산책 또는 문화공간, 취향껏" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "다안삼림공원(대안삼림공원)", desc: "도보로도 이동 가능한 거리에 있는 도심 속 공원입니다. 식사 후 소화도 시킬 겸 녹지를 걷고 싶다면 추천해요." },
            { mark: "2", b: "쑹산문창원구", desc: "MRT로 한두 정거장 거리에 있는 옛 담배공장을 개조한 복합 문화공간입니다. 전시·소품숍을 둘러보며 여유롭게 시간을 보내기 좋아요." },
          ],
        },
        { type: "h2", text: "04 · 동선 팁" },
        {
          type: "tipList",
          items: [
            { mark: "✓", b: "점심 예약이 여유롭습니다", desc: "저녁 시간대는 예약이 더 몰리는 편이라, 오후 코스까지 넉넉히 잡고 싶다면 점심 예약을 노려보세요." },
            { mark: "✓", b: "도보보다 MRT 한두 정거장", desc: "이 일대는 도보로 다니기엔 거리가 애매한 스팟도 있어요. 구글 지도로 MRT 경로를 함께 확인하며 다니는 게 편합니다." },
          ],
        },
        { type: "cta", title: "지도에서 타이베이 맛집도 함께 찜해두세요", desc: "중샤오둔화 근처 맛집과 카페를 지도에서 바로 확인해보세요.", btn: "지도 열기 →", href: "/map?region=taipei" },
        { type: "note", text: "이 글은 베이징덕 전문점 샹덕(享鴨)의 대표 지점 위치와 주변 대중교통 정보를 바탕으로 정리했습니다. 지점별 위치·영업시간·예약 정책은 바뀔 수 있으니 방문 전 공식 채널로 다시 확인해주세요." },
      ],
    },
    en: {
      pageTitle: "What's Near Xiang Duck? A Half-Day Course Around Zhongxiao Dunhua · My Secret Taiwan Eats",
      metaDescription: "Planning a meal at Xiang Duck (享鴨), the reservation-only Peking duck specialist near Zhongxiao Dunhua station? Here's a half-day route through the nearby shopping street, Da'an Forest Park, and Songshan Cultural Park.",
      ogTitle: "What's Near Xiang Duck (享鴨)? A Half-Day Course Around Zhongxiao Dunhua",
      eyebrow: "Taipei Travel Guide · Food Course",
      title: "What's Near Xiang Duck (享鴨)? A Half-Day Course Around Zhongxiao Dunhua",
      dek: "Xiang Duck is known for carving a whole roast duck tableside. Here's a half-day route to fill in the time before or after your reservation.",
      metaAuthor: "My Secret Taiwan Eats Editorial",
      metaTopic: "Taipei · Food Course",
      intro: "Xiang Duck (享鴨) is popular enough that getting a reservation takes some planning. Its main branch sits near <strong>Zhongxiao Dunhua Station</strong>, right where Da'an and Songshan districts meet on Zhongxiao E. Road Section 4. Since you're already making the trip for a reservation, here's a half-day route to round out the visit.",
      blocks: [
        { type: "h2", text: "01 · Before You Book: A Checklist" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "Reservations are essentially required", desc: "The tableside duck-carving is the draw, and walk-ins are difficult — book ahead." },
            { mark: "2", b: "Check for a break time", desc: "Some branches close for a break in the mid-afternoon. Confirm opening hours when you book." },
            { mark: "3", b: "Know how many a whole duck feeds", desc: "A whole duck is usually a good fit for 2-3 people. Ask about ordering options based on your group size." },
          ],
        },
        { type: "h2", text: "02 · Before Your Meal: The Zhongxiao Dunhua Shopping Strip" },
        { type: "p", html: "The area around Zhongxiao Dunhua Station is a shopping strip centered on the SOGO Fuxing branch, with boutiques and concept stores filling the side streets. If you arrive early for your reservation, this is an easy place to kill time — indoors if the weather turns, with everything from department stores to small independent shops." },
        { type: "h2", text: "03 · After Your Meal: A Walk or a Culture Space" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "Da'an Forest Park", desc: "Close enough to reach on foot — a good option if you want greenery and a walk to settle a heavy meal." },
            { mark: "2", b: "Songshan Cultural and Creative Park", desc: "A station or two away by MRT, this converted tobacco factory now houses exhibitions and design shops — good for a slower-paced afternoon." },
          ],
        },
        { type: "h2", text: "04 · Route Tips" },
        {
          type: "tipList",
          items: [
            { mark: "✓", b: "Lunch reservations are easier to get", desc: "Evening slots fill up faster, so if you want a relaxed afternoon route afterward, try booking lunch instead." },
            { mark: "✓", b: "Use the MRT for a stop or two rather than walking everywhere", desc: "Some of these spots are an awkward walking distance apart. Check Google Maps for the MRT route as you go." },
          ],
        },
        { type: "cta", title: "Bookmark More Taipei Restaurants on the Map", desc: "Find restaurants and cafes near Zhongxiao Dunhua, right on the map.", btn: "Open Map →", href: "/map?region=taipei" },
        { type: "note", text: "This guide is based on the location of Xiang Duck's (享鴨) main branch and the public transit around it. Branch locations, hours, and reservation policies can change, so double-check with official channels before you go." },
      ],
    },
  },
  "jiufen-friday-vs-sunday-crowds": {
    heroImage: "assets/images/regions/jiufen.webp",
    ko: {
      pageTitle: "지우펀 방문 타이밍 — 금요일 vs 일요일 혼잡도 비교 · 나만 알고 싶은 대만 맛집",
      metaDescription: "지우펀은 요일마다 혼잡도가 확 다릅니다. 금요일·토요일·일요일, 그리고 낮과 노을 시간대별 체감 혼잡도를 비교하고 덜 붐비게 다니는 방법을 정리했습니다.",
      ogTitle: "지우펀, 금요일 vs 일요일 언제 덜 붐빌까",
      eyebrow: "지우펀 여행 가이드 · 방문 타이밍",
      title: "지우펀, 금요일 vs 일요일 언제 덜 붐빌까",
      dek: "좁은 계단 골목이 명물인 만큼, 방문 요일과 시간대에 따라 체감 혼잡도 차이가 큰 곳이 지우펀입니다. 어린 자녀와 함께라면 더욱 신경 쓰이는 혼잡도 문제를 정리해봤어요.",
      metaAuthor: "나만 알고 싶은 대만 맛집 편집팀",
      metaTopic: "지우펀 · 방문 타이밍",
      intro: "지우펀은 좁은 계단 골목이 매력이자 단점인 곳이에요. 사람이 몰리는 시간대에 가면 사진 한 장 찍기도, 계단을 오르내리기도 쉽지 않죠. 특히 초등학생 자녀와 함께라면 혼잡도가 곧 체력 소모로 이어지니 더 신경 쓰이는 부분입니다. 요일과 시간대에 따라 체감 혼잡도가 얼마나 다른지 정리해봤어요.",
      blocks: [
        { type: "h2", text: "01 · 결론부터 — 일요일이 확실히 더 붐빕니다" },
        { type: "p", html: "일요일은 주말의 마지막 날이라 대만 현지인들의 당일치기 나들이와 단체 투어버스가 한꺼번에 몰리는 날이에요. 반면 금요일은 평일에 가까워 상대적으로 한산한 편이지만, 저녁 시간대로 갈수록 주말 인파가 조금씩 섞이기 시작합니다." },
        {
          type: "compareTable",
          cities: ["금요일", "토요일", "일요일"],
          rows: [
            { label: "낮 시간대 (오전~오후 4시)", values: ["평일에 가까워 비교적 한산합니다", "주말 인파가 본격적으로 몰립니다", "당일치기 인파가 가장 집중되는 시간대예요"] },
            { label: "노을·야경 시간대 (오후 5시 이후)", values: ["주말 초입이라 서서히 붐비기 시작해요", "야경 명소라 특히 혼잡합니다", "일몰 전후로 가장 붐빕니다"] },
            { label: "단체 투어버스", values: ["비교적 적은 편", "많은 편", "가장 많은 편"] },
          ],
        },
        { type: "h2", text: "02 · 그래도 덜 붐비게 다니는 법" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "이른 아침에 움직이기", desc: "어느 요일이든 상점이 문을 열기 전인 오전 9~10시 이전에는 골목이 훨씬 한산합니다." },
            { mark: "2", b: "금요일 낮~이른 저녁을 노리기", desc: "요일 중에서는 금요일 낮 시간대가 가장 여유 있는 편이에요. 저녁까지 이어지는 일정이라면 초저녁까지만 머무는 것도 방법입니다." },
            { mark: "3", b: "계단 골목은 흐름을 거스르지 않기", desc: "혼잡한 시간대에 인파를 거슬러 이동하면 체력 소모가 커집니다. 흐름을 따라 한 방향으로 움직이는 게 수월해요." },
          ],
        },
        { type: "h2", text: "03 · 어린 자녀와 함께라면" },
        { type: "p", html: "계단이 많고 폭이 좁은 골목 구조상, 혼잡한 시간대에는 아이와 함께 이동하기가 특히 힘들어집니다. 늦은 오후~노을 시간대는 사람이 가장 몰리는 때이니, 가능하면 오전이나 이른 오후에 방문을 마치는 일정을 짜는 걸 추천해요. 일정상 요일을 고를 수 있다면 일요일보다는 금요일이 체력적으로 한결 수월합니다." },
        { type: "cta", title: "지우펀 맛집도 지도에서 함께 확인해보세요", desc: "지우펀 노포와 카페를 지도에서 바로 찾아보세요.", btn: "지도 열기 →", href: "/map?region=jiufen" },
        { type: "note", text: "이 글은 여행자들 사이에서 공유되는 요일별·시간대별 체감 혼잡도를 바탕으로 정리했습니다. 실제 혼잡도는 날씨, 공휴일 여부, 현지 행사 일정에 따라 달라질 수 있어요." },
      ],
    },
    en: {
      pageTitle: "Jiufen Timing Guide — Friday vs. Sunday Crowds · My Secret Taiwan Eats",
      metaDescription: "Jiufen's crowd levels swing a lot by day of the week. Here's how Friday, Saturday, and Sunday compare by time of day, and how to visit with fewer crowds.",
      ogTitle: "Jiufen: Friday vs. Sunday, Which Day Is Less Crowded?",
      eyebrow: "Jiufen Travel Guide · Timing Your Visit",
      title: "Jiufen: Friday vs. Sunday, Which Day Is Less Crowded?",
      dek: "Jiufen's narrow stepped alleys are its charm and its biggest challenge — crowd levels swing hard by day and time. Here's what to know, especially if you're traveling with young kids.",
      metaAuthor: "My Secret Taiwan Eats Editorial",
      metaTopic: "Jiufen · Timing Your Visit",
      intro: "Jiufen's narrow stepped alleys are both its charm and its biggest drawback — during peak hours, it's hard to even get a photo, let alone move through the steps comfortably. With young kids in tow, crowding turns straight into exhaustion. Here's how crowd levels actually differ by day and time of day.",
      blocks: [
        { type: "h2", text: "01 · Short Answer: Sunday Is Noticeably Worse" },
        { type: "p", html: "Sunday is the last day of the weekend, which means local day-trippers and tour buses all converge at once. Friday, being closer to a weekday, tends to be quieter — though crowds start building as the evening approaches and the weekend begins." },
        {
          type: "compareTable",
          cities: ["Friday", "Saturday", "Sunday"],
          rows: [
            { label: "Daytime (morning to 4pm)", values: ["Relatively quiet, closer to a weekday", "Weekend crowds in full swing", "The most crowded window of the week"] },
            { label: "Sunset / evening (after 5pm)", values: ["Starts filling up as the weekend begins", "Especially crowded — a well-known night view spot", "Peaks around sunset"] },
            { label: "Tour buses", values: ["Relatively few", "Many", "The most of the week"] },
          ],
        },
        { type: "h2", text: "02 · How to Avoid the Worst of It" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "Go early in the morning", desc: "No matter the day, the alleys are far quieter before shops open around 9-10am." },
            { mark: "2", b: "Aim for Friday daytime to early evening", desc: "Of the three, Friday daytime is the calmest. If your day runs into the evening, try to wrap up before it gets too late." },
            { mark: "3", b: "Move with the flow of foot traffic", desc: "Walking against the crowd on the stepped alleys burns a lot of energy during busy hours. Moving in one direction with everyone else is much easier." },
          ],
        },
        { type: "h2", text: "03 · Traveling with Young Kids" },
        { type: "p", html: "The narrow, stepped layout makes moving through crowds with kids especially tiring. Late afternoon into sunset is the peak window, so plan to wrap up your visit by early afternoon if you can. If you have any flexibility on which day to go, Friday is noticeably easier on everyone's legs than Sunday." },
        { type: "cta", title: "Find Jiufen Restaurants on the Map Too", desc: "Look up Jiufen's old shops and teahouses, right on the map.", btn: "Open Map →", href: "/map?region=jiufen" },
        { type: "note", text: "This guide is based on crowd patterns commonly shared among travelers by day and time. Actual crowd levels can vary with weather, holidays, and local events." },
      ],
    },
  },
  "taipei-longshan-temple-night-guide": {
    heroImage: "assets/images/regions/taipei.webp",
    ko: {
      pageTitle: "용산사 야경 가이드 — 방문 시간대와 완화 야시장 코스 · 나만 알고 싶은 대만 맛집",
      metaDescription: "용산사는 낮보다 저녁 조명이 켜진 뒤 분위기가 완전히 달라집니다. 야경으로 즐기기 좋은 시간대와 화시제·광저우제 야시장, 보피랴오 역사거리까지 묶은 반나절 코스를 정리했습니다.",
      ogTitle: "용산사는 낮보다 밤? 야경 시간대와 주변 코스 짜는 법",
      eyebrow: "타이베이 여행 가이드 · 야경 코스",
      title: "용산사는 낮보다 밤? 야경 시간대와 주변 코스 짜는 법",
      dek: "낮에는 단체 관광객과 참배객으로 붐비는 용산사도, 저녁 조명이 켜지면 완전히 다른 얼굴을 보여줍니다. 야경 방문 타이밍과 완화 지역 야시장을 묶은 코스를 짜봤어요.",
      metaAuthor: "나만 알고 싶은 대만 맛집 편집팀",
      metaTopic: "타이베이 · 야경 코스",
      intro: "용산사는 타이베이에서 손꼽히는 사원이지만, 낮 시간대에는 단체 관광버스와 참배객이 겹쳐 여유롭게 둘러보기가 쉽지 않아요. 반면 해가 진 뒤 조명이 켜지면 붉은 등불과 정교한 지붕 조각이 은은하게 드러나면서 분위기가 확 달라집니다. 야경으로 즐기기 좋은 시간대와, 바로 옆 완화 지역 야시장까지 묶은 반나절 코스를 정리해봤어요.",
      blocks: [
        { type: "h2", text: "01 · 밤에 가면 뭐가 다를까" },
        { type: "p", html: "용산사는 오전 6시부터 오후 10시까지 연중무휴로 운영되고 입장료는 무료입니다. 낮 시간대는 참배객과 단체 관광객이 겹쳐 가장 붐비는 편이고, 해가 완전히 진 뒤에는 관광객 밀도가 낮 시간보다 상대적으로 줄어드는 편이에요. 조명이 켜진 처마와 조각 장식을 가까이서 찬찬히 볼 수 있다는 것도 야간 방문의 장점입니다." },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "해 진 직후가 가장 좋은 타이밍", desc: "하늘이 완전히 어두워지기 전, 노을과 사원 조명이 함께 보이는 시간대가 사진 찍기도 가장 좋습니다." },
            { mark: "2", b: "참배 문화 존중하기", desc: "향을 피우고 기도하는 참배객이 많은 곳이니, 사진을 찍을 때는 방해가 되지 않도록 조용히 움직이는 게 좋습니다." },
            { mark: "3", b: "운영시간은 방문 전 재확인", desc: "행사나 사정에 따라 운영시간이 달라질 수 있으니, 방문 당일 공식 채널로 한 번 더 확인하는 걸 추천해요." },
          ],
        },
        { type: "h2", text: "02 · 완화 지역과 묶어서 반나절 야시장 코스" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "화시제 관광 야시장", desc: "용산사에서 도보 몇 분 거리로, 다양한 먹거리 노점이 모여 있는 관광형 야시장입니다." },
            { mark: "2", b: "광저우제 야시장", desc: "화시제와 이어지는 구간으로, 현지인들도 즐겨 찾는 먹거리 골목이에요." },
            { mark: "3", b: "칭차오샹(청초항)", desc: "약초 상점이 모여 있는 짧은 골목입니다. 독특한 약초 향이 인상적인 완화 지역의 숨은 스팟이에요." },
            { mark: "4", b: "보피랴오 역사거리", desc: "옛 거리 풍경을 그대로 살려둔 구역으로, 야간 조명이 켜지면 산책하기 좋은 분위기가 됩니다." },
          ],
        },
        { type: "h2", text: "03 · 동선 팁" },
        { type: "p", html: "용산사는 MRT 용산사역(블루라인) 출구 바로 앞이라 접근성이 좋습니다. 화시제·광저우제 야시장, 보피랴오 역사거리 모두 도보 5~10분 거리에 모여 있어서, 저녁 식사와 야경 산책을 한 번에 해결하기 좋은 동선이에요." },
        { type: "cta", title: "완화 지역 맛집도 지도에서 확인해보세요", desc: "용산사 주변 노포와 야시장 먹거리를 지도에서 바로 찾아보세요.", btn: "지도 열기 →", href: "/map?region=taipei" },
        { type: "note", text: "이 글은 일반적으로 알려진 용산사 운영시간과 완화 지역 야시장 정보를 바탕으로 정리했습니다. 운영시간과 행사 일정은 바뀔 수 있으니 방문 전 공식 정보로 다시 확인해주세요." },
      ],
    },
    en: {
      pageTitle: "Longshan Temple Night Guide — Timing and a Wanhua Night Market Route · My Secret Taiwan Eats",
      metaDescription: "Longshan Temple looks completely different once the evening lights come on. Here's the best time to visit for the night view, plus a route linking Huaxi Street, Guangzhou Street night markets, and Bopiliao Historic Block.",
      ogTitle: "Longshan Temple: Better at Night Than by Day?",
      eyebrow: "Taipei Travel Guide · Night View Course",
      title: "Longshan Temple: Better at Night Than by Day?",
      dek: "Longshan Temple gets crowded with tour groups and worshippers by day, but once the evening lights come on, it shows a completely different side. Here's the best timing, plus a route through Wanhua's night markets.",
      metaAuthor: "My Secret Taiwan Eats Editorial",
      metaTopic: "Taipei · Night View Course",
      intro: "Longshan Temple is one of Taipei's most-visited temples, but daytime brings a crowd of both tour groups and worshippers, making it hard to take your time. After dark, though, the lit-up red lanterns and intricate roof carvings give the place a completely different mood. Here's when to visit for the night view, plus a half-day route through the neighboring Wanhua night markets.",
      blocks: [
        { type: "h2", text: "01 · What Changes After Dark" },
        { type: "p", html: "Longshan Temple is open daily from 6am to 10pm, with free admission. Daytime tends to be the most crowded, with worshippers and tour groups overlapping, while crowd density generally drops once it's fully dark. Getting a closer, quieter look at the lit-up eaves and carvings is one of the real advantages of visiting at night." },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "Right after sunset is the sweet spot", desc: "Before the sky goes fully dark, the mix of dusk light and temple lighting also makes for the best photos." },
            { mark: "2", b: "Be respectful of worshippers", desc: "This is an active place of worship with incense and prayer. Move quietly and avoid getting in the way when taking photos." },
            { mark: "3", b: "Double-check the hours", desc: "Hours can shift around events, so it's worth confirming through official channels on the day you visit." },
          ],
        },
        { type: "h2", text: "02 · A Half-Day Route Through Wanhua's Night Markets" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "Huaxi Street Tourist Night Market", desc: "A few minutes' walk from the temple, this is a tourist-oriented night market with a wide range of food stalls." },
            { mark: "2", b: "Guangzhou Street Night Market", desc: "Connected to Huaxi Street, this stretch is a food-stall alley that locals frequent too." },
            { mark: "3", b: "Herb Lane (Qingcao Alley)", desc: "A short alley lined with traditional herb shops — a distinctive, lesser-known corner of Wanhua with a strong herbal scent." },
            { mark: "4", b: "Bopiliao Historic Block", desc: "A preserved old street that turns into a pleasant place for an evening stroll once the lights come on." },
          ],
        },
        { type: "h2", text: "03 · Route Tips" },
        { type: "p", html: "Longshan Temple sits right outside the Longshan Temple MRT station exit (Blue Line), so it's easy to reach. Huaxi Street, Guangzhou Street, and Bopiliao Historic Block are all within a 5-10 minute walk, making it easy to combine dinner and an evening walk in one trip." },
        { type: "cta", title: "Find Wanhua Restaurants on the Map Too", desc: "Look up old shops and night market food near Longshan Temple, right on the map.", btn: "Open Map →", href: "/map?region=taipei" },
        { type: "note", text: "This guide is based on commonly known operating hours for Longshan Temple and general information about Wanhua's night markets. Hours and event schedules can change, so double-check with official sources before you go." },
      ],
    },
  },
};
