  "taiwan-mango-shaved-ice-season": {
    heroImage: "assets/images/blog/taiwan-mango-shaved-ice-season-1.jpg",
    ko: {
      pageTitle: "대만 망고빙수 시즌 — 품종별 시기 · 나만 알고 싶은 대만 맛집",
      metaDescription: "대만 망고빙수 시즌은 언제일까요? 애플망고·진황·카이터 품종별 제철과 비수기 냉동 망고 구별 요령을 2026년 기준으로 정리했어요.",
      ogTitle: "대만 망고빙수 시즌, 언제 가야 생망고를 먹을까?",
      eyebrow: "대만 여행 가이드 · 디저트",
      title: "대만 망고빙수 시즌, 언제 가야 생망고를 먹을까?",
      dek: "겨울에 먹은 망고빙수가 기대와 달랐다면 — 품종별 제철을 알고 가면 선택이 쉬워져요.",
      metaAuthor: "나만 알고 싶은 대만 맛집 편집팀",
      metaTopic: "대만 · 디저트 가이드",
      intro: "\"10월에 가도 생망고 빙수 먹을 수 있어요?\" 대만 망고빙수 시즌은 대체로 4월부터 10월까지예요. 다만 품종마다 제철이 달라서 같은 여름이라도 맛이 조금씩 달라요. 농업부 품종 정보와 실제 여행자들의 경험을 바탕으로 시기별로 정리해봤어요.",
      blocks: [
        { type: "h2", text: "01 · 대만 망고빙수 시즌, 품종별 제철 한눈에 보기" },
        {
          type: "compareTable",
          cities: ["제철", "특징"],
          rows: [
            { label: "토종 망고", values: ["4월부터", "작고 향이 진한 편"] },
            { label: "아이원(愛文, 애플망고)", values: ["4월 말~7월 말, 5~6월이 절정", "빙수에 가장 많이 쓰이는 품종"] },
            { label: "진황(金煌)", values: ["5~8월", "크고 과육이 많은 편"] },
            { label: "카이터(凱特)", values: ["8~10월", "늦여름·가을에 나오는 품종"] },
          ],
        },
        { type: "h2", text: "02 · 비수기에는 냉동 망고일 수 있어요" },
        { type: "p", html: "제철이 아닌 겨울·초봄에도 망고빙수를 파는 가게가 있지만, 이때는 냉동 망고를 쓰는 경우가 많아요. 생망고 사용 여부는 가게 공지나 메뉴판에 적어두는 곳이 많으니 주문 전에 확인해보세요. 가을에 간다면 카이터 품종을 쓰는지 물어보는 것도 방법이에요." },
        { type: "figure", img: "assets/images/blog/taiwan-mango-shaved-ice-season-1.jpg", caption: "격자 모양으로 칼집을 내 뒤집은 생망고예요(빙수 사진 아님). 제철 망고는 과육 색이 진하고 향이 강해요." },
        { type: "h2", text: "03 · 망고빙수 주문 요령" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "시즌 한정 메뉴 확인", desc: "제철에만 파는 생망고 메뉴가 따로 있는 가게가 많아요." },
            { mark: "2", b: "둘이서 하나", desc: "양이 많은 편이라 둘이 하나를 나눠 먹는 여행자가 많아요." },
            { mark: "3", b: "오전이나 늦은 오후", desc: "한여름 오후에는 줄이 길어지기 쉬워요." },
            { mark: "4", b: "가격은 가게마다", desc: "생망고 메뉴는 시세에 따라 가격이 바뀌어요. 이 글에는 가격을 적지 않았어요." },
            { mark: "5", b: "생망고만 사 먹기", desc: "빙수 대신 과일가게에서 제철 망고를 사서 숙소에서 먹는 여행자도 많아요. 망고는 한국으로 가져갈 수 없으니 현지에서 다 드세요." },
          ],
        },
        { type: "h2", text: "04 · 여행 시기별 추천" },
        { type: "p", html: "5~6월에 간다면 아이원 망고가 가장 맛있을 때라 망고빙수를 일정에 꼭 넣어볼 만해요. 7~8월은 진황까지 나와 선택지가 넓어지고, 9~10월은 카이터 위주예요. 11월부터 3월 사이라면 망고보다 딸기나 팥 같은 겨울 빙수를 고르는 여행자도 많아요." },
        { type: "quote", text: "\"망고빙수는 5~6월, 그 밖에는 생망고인지 물어보기.\" — 계절마다 대만 빙수를 먹어 본 여행자들의 조언을 요약했습니다." },
        { type: "p", html: "망고 산지와 가까운 타이난에는 빙수 가게가 많아요. <a href=\"/tainan-shaved_ice\">타이난 빙수 맛집</a> 모음에서 망고빙수 가게 <a href=\"/tainan-shaved_ice-788\">위메이 망고빙(玉梅芒果冰)</a>을 볼 수 있고, 주변 식당은 <a href=\"/region-tainan\">타이난 맛집 지도</a>에 있어요. 타이베이에서 먹는다면 <a href=\"/taipei-shaved_ice\">타이베이 빙수 맛집</a>을 참고하세요." },
        { type: "note", text: "이 글은 대만 농업부 품종 정보와 여행자들의 경험을 바탕으로 정리했습니다(2026년 9월 기준). 산지 날씨에 따라 수확 시기가 달라질 수 있어요." },
        { type: "cta", title: "지도에서 타이난 빙수 맛집을 찾아보세요", desc: "망고 산지와 가까운 타이난의 빙수 가게를 지도에서 확인해보세요.", btn: "지도 열기 →", href: "/map?region=tainan&cat=shaved_ice" },
      ],
    },
    en: {
      pageTitle: "Taiwan Mango Shaved Ice Season — Varieties and Timing · My Secret Taiwan Eats",
      metaDescription: "Taiwan's mango season runs roughly April to October. Peak months by variety and how to tell if a shop uses frozen mango.",
      ogTitle: "Taiwan Mango Shaved Ice Season: When Can You Get Fresh Mango?",
      eyebrow: "Taiwan Travel Guide · Desserts",
      title: "Taiwan Mango Shaved Ice Season: When Can You Get Fresh Mango?",
      dek: "If a winter mango ice disappointed you — knowing each variety's season makes choosing easier.",
      metaAuthor: "My Secret Taiwan Eats Editorial",
      metaTopic: "Taiwan · Dessert Guide",
      intro: "\"Can I get fresh mango shaved ice in October?\" Taiwan's mango season runs roughly April to October, but each variety peaks at a different time. Based on Ministry of Agriculture variety information and real traveler experiences, here's the timing.",
      blocks: [
        { type: "h2", text: "01 · Peak Season by Variety" },
        {
          type: "compareTable",
          cities: ["Season", "Notes"],
          rows: [
            { label: "Native mango", values: ["From April", "Small and fragrant"] },
            { label: "Irwin (愛文)", values: ["Late April–late July, peak May–June", "The most common shaved-ice variety"] },
            { label: "Jinhwang (金煌)", values: ["May–August", "Large and fleshy"] },
            { label: "Keitt (凱特)", values: ["August–October", "A late-summer and autumn variety"] },
          ],
        },
        { type: "h2", text: "02 · Off-Season Mango May Be Frozen" },
        { type: "p", html: "Some shops sell mango ice in winter and early spring, but it's often frozen mango then. Many shops note fresh mango on their menus or notices, so check before ordering. In autumn, ask whether they're using Keitt." },
        { type: "figure", img: "assets/images/blog/taiwan-mango-shaved-ice-season-1.jpg", caption: "Fresh mango scored in a grid and turned out (not shaved ice). In-season mango has deep color and strong aroma." },
        { type: "h2", text: "03 · Ordering Tips" },
        {
          type: "tipList",
          items: [
            { mark: "1", b: "Look for seasonal menus", desc: "Many shops have a fresh-mango item only in season." },
            { mark: "2", b: "Share one", desc: "Portions are big, so many travelers split one." },
            { mark: "3", b: "Go mid-morning or late afternoon", desc: "Lines grow on summer afternoons." },
            { mark: "4", b: "Prices vary", desc: "Fresh-mango prices follow the market, so none are listed here." },
            { mark: "5", b: "Just buy the fruit", desc: "Many travelers buy in-season mangoes at a fruit stand and eat them at the hotel. Fresh mangoes can't be brought into Korea, so finish them in Taiwan." },
          ],
        },
        { type: "h2", text: "04 · By Travel Month" },
        { type: "p", html: "May–June is Irwin's peak, so mango ice is a must. July–August adds Jinhwang, and September–October is mostly Keitt. From November to March, many travelers choose winter ices like strawberry or red bean instead." },
        { type: "quote", text: "\"Mango ice in May–June; other months, ask if it's fresh.\" — a summary of advice from travelers who've eaten Taiwanese shaved ice across seasons." },
        { type: "p", html: "Tainan, close to mango country, has plenty of shaved ice shops. See <a href=\"/tainan-shaved_ice\">Tainan shaved ice spots</a>, including the mango ice shop <a href=\"/tainan-shaved_ice-788\">Yumei Mango Ice (玉梅芒果冰)</a>, and nearby food on the <a href=\"/region-tainan\">Tainan food map</a>. In Taipei, check <a href=\"/taipei-shaved_ice\">Taipei shaved ice spots</a>." },
        { type: "note", text: "Based on Taiwan Ministry of Agriculture variety information and traveler experiences (as of September 2026). Harvests can shift with weather." },
        { type: "cta", title: "Find Tainan shaved ice on the map", desc: "Check shaved ice shops in Tainan, close to mango country.", btn: "Open Map →", href: "/map?region=tainan&cat=shaved_ice" },
      ],
    },
  }
